#!/usr/bin/env python3
"""Render .runtime/alertmanager/alertmanager.yml from the environment.

WHY A RENDERER AND NOT A COMMITTED FILE. Alertmanager does not expand
environment variables in its configuration, and the SMTP password must never
enter the repository. The settings live in .runtime/secrets.env (password) and
.env (host, port, addresses) like every other secret on this box, and this
script writes the one file Alertmanager reads, mode 0600.

WITH NO MAIL SETTINGS THE ALERTS STILL GO SOMEWHERE. The receiver is then the
null receiver: Alertmanager starts, groups and deduplicates as usual, and the
alert list stays visible at its own URL and in Grafana. A missing password is
not a reason to leave the notifier out of the stack.

Read by scripts/monitoring.sh before `docker compose up`, and unit-tested in
launcher/tests/test_alertmanager_config.py.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Mapping

REQUIRED_FOR_EMAIL = ("ALERT_EMAIL_TO", "ALERT_SMTP_HOST")

# Alertmanager's own defaults resend a firing alert every 4 hours. On one box
# with one operator that is the right cadence: the first mail is immediate,
# a repeat says "still down", and a flapping service cannot fill an inbox.
GROUP_WAIT = "30s"
GROUP_INTERVAL = "5m"
REPEAT_INTERVAL = "4h"


def _yaml_quote(value: str) -> str:
    """Single-quoted YAML scalar: the only escape inside is a doubled quote."""
    return "'" + str(value).replace("'", "''") + "'"


def _truthy(value: str | None) -> bool:
    return str(value or "").strip().lower() in ("1", "true", "yes", "on")


def render(env: Mapping[str, str]) -> str:
    """The alertmanager.yml text for this environment."""
    to = (env.get("ALERT_EMAIL_TO") or "").strip()
    host = (env.get("ALERT_SMTP_HOST") or "").strip()
    email = bool(to and host)
    port = (env.get("ALERT_SMTP_PORT") or "587").strip() or "587"
    sender = (env.get("ALERT_EMAIL_FROM") or "").strip() or (
        env.get("ALERT_SMTP_USER") or ""
    ).strip() or "alertmanager@localhost"
    user = (env.get("ALERT_SMTP_USER") or "").strip()
    password = env.get("ALERT_SMTP_PASSWORD") or ""
    # Port 465 is implicit TLS; 587 and 25 start plaintext and upgrade with
    # STARTTLS. require_tls is Alertmanager's STARTTLS switch, so it must be
    # false on 465 or the handshake is attempted twice.
    require_tls = _truthy(env.get("ALERT_SMTP_STARTTLS") or ("false" if port == "465" else "true"))
    lines = [
        "# GENERATED by monitoring/alertmanager/render_config.py. Do not edit:",
        "# `scripts/monitoring.sh up` overwrites this file from .env and",
        "# .runtime/secrets.env. It holds the SMTP password, so it is 0600 and",
        "# .runtime/ is ignored by git.",
        "global:",
        f"  resolve_timeout: 5m",
    ]
    if email:
        lines += [
            f"  smtp_smarthost: {_yaml_quote(host + ':' + port)}",
            f"  smtp_from: {_yaml_quote(sender)}",
            f"  smtp_require_tls: {'true' if require_tls else 'false'}",
        ]
        if user:
            lines.append(f"  smtp_auth_username: {_yaml_quote(user)}")
        if password:
            lines.append(f"  smtp_auth_password: {_yaml_quote(password)}")
    lines += [
        "",
        "route:",
        "  # One group per alert name and instance: a node that drops takes",
        "  # several rules with it, and they belong in one mail.",
        "  group_by: ['alertname', 'instance']",
        f"  group_wait: {GROUP_WAIT}",
        f"  group_interval: {GROUP_INTERVAL}",
        f"  repeat_interval: {REPEAT_INTERVAL}",
        f"  receiver: {_yaml_quote('email' if email else 'null')}",
        "",
        "receivers:",
        "  - name: 'null'",
    ]
    if email:
        # Alertmanager takes ONE comma-separated string here, not a list.
        recipients = ", ".join(a.strip() for a in to.split(",") if a.strip())
        lines += [
            "  - name: 'email'",
            "    email_configs:",
            f"      - to: {_yaml_quote(recipients)}",
            "        send_resolved: true",
            "        headers:",
            "          subject: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}"
            " on {{ .CommonLabels.instance }}'",
        ]
    lines += [
        "",
        "inhibit_rules:",
        "  # A critical alert on a target silences its warning twin: one",
        "  # outage, one mail.",
        "  - source_matchers: ['severity = critical']",
        "    target_matchers: ['severity = warning']",
        "    equal: ['alertname', 'instance']",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    out = Path(argv[1]) if len(argv) > 1 else Path(".runtime/alertmanager/alertmanager.yml")
    out.parent.mkdir(parents=True, exist_ok=True)
    text = render(os.environ)
    out.write_text(text, encoding="utf-8")
    out.chmod(0o600)
    configured = bool((os.environ.get("ALERT_EMAIL_TO") or "").strip()
                      and (os.environ.get("ALERT_SMTP_HOST") or "").strip())
    print(
        f"alertmanager config: {out} ("
        + ("email to " + os.environ["ALERT_EMAIL_TO"] if configured
           else "no ALERT_EMAIL_TO/ALERT_SMTP_HOST: alerts stay in the UI")
        + ")"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised through main()
    raise SystemExit(main(sys.argv))
