#!/usr/bin/env python3
"""One-shot data migration: /data/app.sqlite3 -> the PostgreSQL app database.

Run it ONCE, after `db.init_schema()` has created the target schema (starting
the orchestrator does that; so does `--init-schema` here).

    # from the host, against the loopback-published compose service
    orchestrator/.venv/bin/python orchestrator/scripts/migrate_sqlite_to_postgres.py \
        --sqlite /var/lib/docker/volumes/sf-local-ai_data/_data/app.sqlite3 \
        --dsn postgresql://techsara:PASSWORD@127.0.0.1:5432/techsara

    # or a rehearsal that touches nothing:
    ... --dry-run

WHAT IT IS CAREFUL ABOUT — the four things that quietly corrupt this kind of
migration:

1. IDENTITY SEQUENCES. Rows are inserted with their original ids so that
   `messages.id` ordering, and every `ORDER BY id` that depends on it, is
   preserved exactly. A `GENERATED BY DEFAULT AS IDENTITY` sequence does not
   notice explicit inserts, so without the `setval` pass at the end the very
   next INSERT collides on the primary key. This is the classic post-migration
   bug and the reason `--verify` checks it.

2. TEXT -> timestamptz. SQLite stored `datetime.now(timezone.utc).isoformat()`
   as text. Parsed here and inserted as real timestamps, so the values that
   come back out `.isoformat()` to the identical strings.

3. ORPHANS. `uploads`, `url_documents`, `repos`, `repo_chunks` and `documents`
   have NO foreign key — in PostgreSQL exactly as in SQLite, because `/chat`
   supports a conversation that has no `conversations` row at all. Rows of
   theirs pointing at a deleted conversation are the residue of DATA-03; they
   are COPIED unchanged and merely reported, because dropping a user's content
   is not this script's decision. The three tables that do declare the key
   (`messages`, `conversation_summaries`, `conversation_chunks`) declared it
   under SQLite too, so an orphan there means a corrupt source — those are
   quarantined to a JSON file rather than aborting the run.

4. RE-RUNS. Refuses to touch a target that already holds rows unless
   `--truncate` is given, so a second accidental run cannot double the history.
"""
from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

# Insertion order matters: parents before children, or the foreign keys fire.
TABLES: Tuple[str, ...] = (
    "users",
    "conversations",
    "messages",
    "conversation_summaries",
    "conversation_chunks",
    "uploads",
    "url_documents",
    "documents",
    "repos",
    "repo_chunks",
)

#: table -> columns whose SQLite TEXT value is an ISO-8601 timestamp.
TIMESTAMP_COLUMNS: Dict[str, Tuple[str, ...]] = {
    "users": ("created_at",),
    "conversations": ("created_at", "updated_at"),
    "messages": ("created_at",),
    "conversation_summaries": ("updated_at",),
    "conversation_chunks": ("created_at",),
    "uploads": ("created_at",),
    "url_documents": ("fetched_at",),
    "documents": ("created_at",),
    "repos": ("cloned_at",),
    "repo_chunks": (),
}

#: table -> columns holding 0/1 that become real booleans.
BOOLEAN_COLUMNS: Dict[str, Tuple[str, ...]] = {"conversations": ("pinned", "archived")}

#: table -> columns holding a JSON string that becomes jsonb.
JSON_COLUMNS: Dict[str, Tuple[str, ...]] = {
    "messages": ("meta",),
    "uploads": ("profile",),
}

#: table -> columns holding raw bytes.
BYTES_COLUMNS: Dict[str, Tuple[str, ...]] = {"conversation_chunks": ("embedding",)}

#: Tables whose `conversation_id` really is a foreign key, so a row pointing at
#: a conversation that no longer exists CANNOT be inserted. These three were
#: already declared (and enforced, via PRAGMA foreign_keys=ON) under SQLite, so
#: an orphan here would be a corrupt source database rather than normal drift.
FK_CHILDREN: Tuple[str, ...] = (
    "messages",
    "conversation_summaries",
    "conversation_chunks",
)

#: Tables keyed by conversation_id with NO foreign key, matching SQLite. Their
#: orphans are migrated as-is — they are the residue of DATA-03 (deletes that
#: never cleaned up), and dropping user content is not this script's call. They
#: are reported so the count is visible, and `delete_conversation` stops
#: creating new ones.
LOOSE_CHILDREN: Tuple[str, ...] = (
    "uploads",
    "url_documents",
    "documents",
    "repos",
    "repo_chunks",
)

#: table -> identity column whose sequence must be advanced past the copied ids.
IDENTITY_COLUMNS: Dict[str, Tuple[str, ...]] = {
    "users": ("id",),
    "conversations": ("seq",),
    "messages": ("id",),
    "conversation_chunks": ("id",),
    "url_documents": ("id",),
    "documents": ("id",),
    "repos": ("id",),
    "repo_chunks": ("id",),
}


def parse_ts(value: Any, column: str) -> Optional[datetime]:
    """ISO-8601 text -> aware datetime. Anything unparseable is a hard error:
    silently defaulting a timestamp is worse than refusing to migrate."""
    if value is None:
        return None
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    text = str(value).strip()
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError as exc:
        raise SystemExit(f"unparseable timestamp in {column}: {value!r} ({exc})")
    # A naive value can only have come from a UTC-generating call site.
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


def to_jsonb(value: Any) -> Optional[Jsonb]:
    if value is None:
        return None
    if isinstance(value, (dict, list)):
        return Jsonb(value)
    try:
        return Jsonb(json.loads(value))
    except (TypeError, ValueError):
        # Preserve it rather than lose it; the app reads this back as an object.
        return Jsonb({"raw": str(value)})


def sqlite_columns(con: sqlite3.Connection, table: str) -> List[str]:
    return [r[1] for r in con.execute(f"PRAGMA table_info({table})")]


def target_columns(pg: psycopg.Connection, table: str) -> List[str]:
    rows = pg.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema = 'public' AND table_name = %s ORDER BY ordinal_position",
        (table,),
    ).fetchall()
    return [r["column_name"] for r in rows]


def read_rows(con: sqlite3.Connection, table: str, columns: Sequence[str]) -> List[dict]:
    select = ", ".join(f'"{c}"' for c in columns)
    return [dict(r) for r in con.execute(f"SELECT {select} FROM {table}")]


def adapt(table: str, row: dict) -> dict:
    out = dict(row)
    for col in TIMESTAMP_COLUMNS.get(table, ()):
        if col in out:
            out[col] = parse_ts(out[col], f"{table}.{col}")
    for col in BOOLEAN_COLUMNS.get(table, ()):
        if col in out:
            out[col] = bool(out[col])
    for col in JSON_COLUMNS.get(table, ()):
        if col in out:
            out[col] = to_jsonb(out[col])
    for col in BYTES_COLUMNS.get(table, ()):
        if col in out and out[col] is not None:
            out[col] = bytes(out[col])
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sqlite", required=True, help="path to the old app.sqlite3")
    ap.add_argument(
        "--dsn",
        default=os.environ.get("APP_DATABASE_URL", ""),
        help="target PostgreSQL DSN (default: $APP_DATABASE_URL)",
    )
    ap.add_argument("--dry-run", action="store_true", help="read and validate, write nothing")
    ap.add_argument(
        "--truncate",
        action="store_true",
        help="DELETE every existing app row first (required to re-run)",
    )
    ap.add_argument(
        "--init-schema",
        action="store_true",
        help="apply app.db migrations to the target before copying",
    )
    ap.add_argument(
        "--quarantine",
        default="orphaned-rows.json",
        help="where to write rows rejected by the new foreign keys",
    )
    args = ap.parse_args()

    if not args.dsn:
        ap.error("--dsn (or APP_DATABASE_URL) is required")
    src_path = Path(args.sqlite)
    if not src_path.exists():
        ap.error(f"no such SQLite database: {src_path}")

    if args.init_schema:
        sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
        from app.config import settings  # noqa: E402
        from app import db as appdb  # noqa: E402

        settings.app_database_url = args.dsn
        appdb.init_schema()
        appdb.close_pool()
        print(f"schema applied to {args.dsn.rsplit('@', 1)[-1]}")

    con = sqlite3.connect(f"file:{src_path}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row

    with psycopg.connect(args.dsn, row_factory=dict_row, autocommit=False) as pg:
        # --- pre-flight -----------------------------------------------------
        missing = [
            t
            for t in TABLES
            if not pg.execute("SELECT to_regclass(%s) AS r", (f"public.{t}",)).fetchone()["r"]
        ]
        if missing:
            print(f"ERROR: target is missing tables {missing}. Run with --init-schema.")
            return 2

        existing = {
            t: pg.execute(f"SELECT COUNT(*) AS n FROM {t}").fetchone()["n"] for t in TABLES
        }
        occupied = {t: n for t, n in existing.items() if n}
        if occupied and not args.truncate:
            print(f"ERROR: target already holds rows {occupied}.")
            print("       Re-running would duplicate history. Pass --truncate to replace it.")
            return 2

        # --- read + adapt ---------------------------------------------------
        conversation_ids = {
            r["id"] for r in con.execute("SELECT id FROM conversations")
        }
        payload: Dict[str, List[dict]] = {}
        orphans: Dict[str, List[dict]] = {}
        loose_orphans: Dict[str, int] = {}
        for table in TABLES:
            src_cols = sqlite_columns(con, table)
            if not src_cols:
                payload[table] = []
                continue
            dst_cols = set(target_columns(pg, table))
            # `conversations.seq` has no SQLite counterpart — it replaces the
            # implicit rowid the sidebar ordering used as its tiebreak, so copy
            # the rowid into it and insertion order survives the move.
            select_cols = [c for c in src_cols if c in dst_cols]
            dropped = [c for c in src_cols if c not in dst_cols]
            if dropped:
                print(f"  note: {table} columns not present in the target: {dropped}")
            if table == "conversations":
                rows = [
                    dict(r)
                    for r in con.execute(
                        f"SELECT {', '.join(select_cols)}, rowid AS seq FROM conversations"
                    )
                ]
            else:
                rows = read_rows(con, table, select_cols)

            kept, rejected = rows, []
            if table in FK_CHILDREN:
                # A real constraint would reject these, so they cannot be
                # copied — quarantine rather than abort the whole migration.
                kept, rejected = [], []
                for r in rows:
                    (kept if r.get("conversation_id") in conversation_ids else rejected).append(r)
                if rejected:
                    orphans[table] = rejected
            elif table in LOOSE_CHILDREN:
                loose_orphans[table] = sum(
                    1 for r in rows if r.get("conversation_id") not in conversation_ids
                )
            payload[table] = [adapt(table, r) for r in kept]

        print("\nsource rows to copy:")
        for table in TABLES:
            n_rejected = len(orphans.get(table, []))
            n_loose = loose_orphans.get(table, 0)
            flag = ""
            if n_rejected:
                flag = f"   <-- {n_rejected} REJECTED by a foreign key"
            elif n_loose:
                flag = f"   ({n_loose} of these are orphans, copied as-is)"
            print(f"  {table:<24} {len(payload[table]):>7}{flag}")

        if loose_orphans and any(loose_orphans.values()):
            total = sum(loose_orphans.values())
            print(
                f"\n  note: {total} row(s) reference a conversation that no longer "
                "exists — residue of DATA-03, where deleting a conversation left its\n"
                "        uploads/pages/repo chunks behind. They are migrated unchanged "
                "(dropping user content is not this script's call);\n"
                "        delete_conversation now clears them, so no new ones appear."
            )

        if orphans:
            out = Path(args.quarantine)
            out.write_text(json.dumps(orphans, indent=2, default=str))
            total = sum(len(v) for v in orphans.values())
            print(
                f"\n  WARNING: {total} row(s) in {sorted(orphans)} violate a foreign key "
                f"that SQLite also declared — the source database is inconsistent.\n"
                f"  They were NOT copied. Written to {out} so nothing is lost."
            )

        if args.dry_run:
            print("\n--dry-run: nothing written.")
            return 0

        # --- write ----------------------------------------------------------
        if args.truncate:
            # One statement: CASCADE follows the same foreign keys, and RESTART
            # IDENTITY rewinds the sequences so a fresh copy starts clean.
            pg.execute(
                "TRUNCATE TABLE " + ", ".join(TABLES) + " RESTART IDENTITY CASCADE"
            )
            print("\ntarget truncated")

        print()
        for table in TABLES:
            rows = payload[table]
            if not rows:
                print(f"  {table:<24} 0")
                continue
            cols = list(rows[0].keys())
            # OVERRIDING SYSTEM VALUE is not needed (the identity columns are
            # GENERATED BY DEFAULT), but the ids must be explicit for ordering.
            placeholders = ", ".join(["%s"] * len(cols))
            stmt = (
                f'INSERT INTO {table} ({", ".join(chr(34) + c + chr(34) for c in cols)}) '
                f"VALUES ({placeholders})"
            )
            pg.cursor().executemany(stmt, [tuple(r[c] for c in cols) for r in rows])
            print(f"  {table:<24} {len(rows)} inserted")

        # --- sequences ------------------------------------------------------
        # Without this the next INSERT reuses id 1 and fails on the PK.
        print()
        for table, columns in IDENTITY_COLUMNS.items():
            for column in columns:
                row = pg.execute(
                    f"SELECT pg_get_serial_sequence(%s, %s) AS seq, "
                    f'COALESCE(MAX("{column}"), 0) AS hi FROM {table}',
                    (table, column),
                ).fetchone()
                if not row["seq"]:
                    continue
                # is_called=true so nextval() returns hi+1, not hi.
                pg.execute(
                    "SELECT setval(%s, GREATEST(%s, 1), %s)",
                    (row["seq"], row["hi"], bool(row["hi"])),
                )
                print(f"  sequence {table}.{column:<10} -> next id {int(row['hi']) + 1}")

        pg.commit()

        # --- verify ---------------------------------------------------------
        print("\nverification:")
        ok = True
        for table in TABLES:
            want = len(payload[table])
            got = pg.execute(f"SELECT COUNT(*) AS n FROM {table}").fetchone()["n"]
            mark = "ok " if want == got else "FAIL"
            ok &= want == got
            print(f"  {mark} {table:<24} expected {want:<7} found {got}")

        # A round-trip spot check on the three conversions most likely to be
        # silently wrong: timestamp text, JSON, and the 0/1 flags.
        sample = pg.execute(
            "SELECT id, created_at, updated_at, pinned, archived FROM conversations "
            "ORDER BY seq LIMIT 1"
        ).fetchone()
        if sample:
            src = con.execute(
                "SELECT created_at, updated_at, pinned, archived FROM conversations "
                "WHERE id = ?",
                (sample["id"],),
            ).fetchone()
            same_created = sample["created_at"].isoformat() == src["created_at"]
            same_updated = sample["updated_at"].isoformat() == src["updated_at"]
            same_flags = (sample["pinned"] == bool(src["pinned"])) and (
                sample["archived"] == bool(src["archived"])
            )
            ok &= same_created and same_updated and same_flags
            print(
                f"  {'ok ' if same_created and same_updated else 'FAIL'} timestamps "
                f"round-trip to the identical ISO-8601 string "
                f"({sample['created_at'].isoformat()})"
            )
            print(f"  {'ok ' if same_flags else 'FAIL'} pinned/archived flags preserved")

        meta_row = pg.execute(
            "SELECT meta FROM messages WHERE meta IS NOT NULL LIMIT 1"
        ).fetchone()
        if meta_row:
            good = isinstance(meta_row["meta"], (dict, list))
            ok &= good
            print(f"  {'ok ' if good else 'FAIL'} messages.meta reads back as JSON")

        chunk = pg.execute(
            "SELECT length(embedding) AS n FROM conversation_chunks LIMIT 1"
        ).fetchone()
        if chunk:
            print(f"  ok  conversation_chunks.embedding {chunk['n']} bytes")

    con.close()
    print("\nDONE" if ok else "\nFINISHED WITH FAILURES — do not delete the SQLite file")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
