"""The labelled prompt set for the Fast adaptive-thinking classifier.

Written for this purpose (2026-09-15) — no prompt is copied from a user
conversation. MUST_THINK are multi-step reasoning tasks a thinking-off answer
tends to get wrong or loop on; MUST_NOT are tasks where a thinking pass only
adds latency: greetings, chit-chat, factual lookups (many with numbers that
need no reasoning), summaries, translations, writing tasks and live values.
Languages: English, Hindi (Latin and Devanagari), Gujarati (script and Latin)
and Hinglish.
"""

MUST_THINK = [
    # --- the owner's report, paraphrased as a fresh prompt ---
    "I have hot water and cold water and one empty bottle whose capacity I don't know. No measuring tools. How do I fill the bottle with hot and cold water in a 2:5 ratio?",
    # --- measurement / containers ---
    "You have a 3 litre jug and a 5 litre jug and unlimited water. How can you measure exactly 4 litres?",
    "With only a 7 litre bucket and a 4 litre bucket, how do I get exactly 6 litres of water?",
    "Mere paas 5 litre aur 3 litre ki do balti hai, exactly 4 litre paani kaise naapu?",
    "मेरे पास 8 लीटर और 5 लीटर के दो बर्तन हैं। ठीक 3 लीटर पानी कैसे नापें?",
    "મારી પાસે 5 લિટર અને 3 લિટરની બે ડોલ છે. બરાબર 4 લિટર પાણી કેવી રીતે માપવું?",
    "Two containers hold 9 and 4 cups. Using only them, measure 6 cups of milk.",
    # --- ratio / mixture ---
    "A mixture contains milk and water in the ratio 3:2. If 10 litres of water is added the ratio becomes 3:4. How much milk is there?",
    "Divide 1400 rupees between A and B in the ratio 3:4.",
    "Doodh aur paani ka anupat 4:1 hai, 25 litre mixture me kitna paani hai?",
    "एक मिश्रण में दूध और पानी का अनुपात 5:3 है। 40 लीटर मिश्रण में कितना दूध है?",
    "દૂધ અને પાણીનો ગુણોત્તર 3:1 છે. 24 લિટર મિશ્રણમાં કેટલું પાણી છે?",
    "Cement, sand and gravel are mixed in the ratio 1:2:4 to make 350 kg of concrete. How much sand is needed?",
    # --- word problems ---
    "A train leaves Delhi at 60 km/h and another leaves Agra at 90 km/h towards it. The cities are 200 km apart. When do they meet?",
    "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?",
    "If 5 machines take 5 minutes to make 5 widgets, how long would 100 machines take to make 100 widgets?",
    "Ravi is twice as old as Sita. 6 years ago he was three times as old as her. How old is Sita now?",
    "A shopkeeper buys a shirt for 400 and sells it at a 25% profit after giving a 10% discount on the marked price. What is the marked price?",
    "Pipe A fills a tank in 6 hours and pipe B empties it in 9 hours. If both are open, how long will it take to fill the tank?",
    "What is the compound interest on 50,000 at 8% per annum for 3 years compounded yearly?",
    "A car travels 120 km at 40 km/h and returns at 60 km/h. What is the average speed for the whole trip?",
    "Ek train 72 km/h ki raftar se 150 meter lambi platform ko 15 second me paar karti hai, train ki lambai kitni hai?",
    "Ram ke paas 250 rupaye the, usne 3 pen 35 rupaye ke hisab se kharide, ab uske paas kitne rupaye bache?",
    "राम की उम्र श्याम से 4 वर्ष अधिक है। 5 वर्ष पहले दोनों की उम्र का योग 30 था। राम की वर्तमान उम्र कितनी है?",
    "एक काम को A 10 दिन में और B 15 दिन में करता है। दोनों मिलकर कितने दिन में करेंगे?",
    "એક ટ્રેન 60 કિમી/કલાકની ઝડપે 3 કલાક ચાલે છે અને પછી 80 કિમી/કલાકે 2 કલાક. કુલ અંતર કેટલું થયું?",
    "રમેશ પાસે 500 રૂપિયા હતા. તેણે 4 પુસ્તક 85 રૂપિયાના ભાવે લીધા. હવે કેટલા રૂપિયા બાકી છે?",
    "Maari paase 12 keri che ane 3 mitro ma sarkhi vaheshu to dar ek ne ketli malse ane 2 vadhare aapu to ketli bachse?",
    "A tank is 3/4 full. After using 30 litres it is 1/2 full. What is the capacity of the tank?",
    "If a clock shows 3:15, what is the angle between the hour and minute hands?",
    "A snail climbs 3 m up a 10 m well each day and slips back 2 m each night. On which day does it get out?",
    "I earn 45,000 a month, rent is 30% of it, food is 1/4 of what remains. How much is left after both?",
    # --- arithmetic worth doing carefully ---
    "What is 347 * 29?",
    "Calculate 15% of 2400 plus 8% of 1250.",
    "(125 + 375) / 4 - 17 * 3 = ?",
    "18% GST on 12,450 rupees — what's the final amount including tax?",
    # --- equations / algebra / calculus ---
    "Solve 3x + 7 = 22 and explain the steps.",
    "Solve for x: x^2 - 5x + 6 = 0",
    "Find two numbers whose sum is 50 and difference is 14.",
    "Differentiate f(x) = x^3 sin(x).",
    "2x + 3y = 12 aur x - y = 1 ko hal karo",
    "समीकरण 4x - 9 = 3x + 2 को हल कीजिए",
    # --- proofs / derivations / why exactly ---
    "Prove that the square root of 2 is irrational.",
    "Derive the formula for the sum of the first n natural numbers.",
    "Show that the sum of two odd numbers is always even.",
    "Why exactly does the Monty Hall switch strategy win two thirds of the time?",
    "सिद्ध कीजिए कि किसी त्रिभुज के कोणों का योग 180 डिग्री होता है।",
    "સાબિત કરો કે બે ક્રમિક પૂર્ણાંકોનો ગુણાકાર હંમેશા બેકી હોય છે.",
    # --- combinatorics / probability ---
    "How many ways can the letters of the word BANANA be arranged?",
    "What is the probability of getting at least one six in four rolls of a die?",
    "In a room of 10 people everyone shakes hands once. How many handshakes are there?",
    "5 log ek line me kitne tarike se khade ho sakte hain agar 2 log hamesha saath rahe?",
    # --- logic ---
    "A says B is lying. B says C is lying. C says both A and B are lying. Who is telling the truth?",
    "On an island of knights and knaves, one person says 'at least one of us is a knave'. What are they?",
    "If all bloops are razzies and all razzies are lazzies, are all bloops definitely lazzies?",
    "Five friends sit in a row. Amit is left of Bina, Chetan is at one end, Dev is next to Bina. Who sits in the middle? Seating arrangement puzzle.",
    "Teen dost hain, ek hamesha sach bolta hai, ek hamesha jhooth, ek kabhi bhi. Kaun jhooth bol raha hai kaise pata karein?",
    "Here's a riddle: what has keys but can't open locks?",
    "Ek paheli bujho: aisi kaunsi cheez hai jo jitna badhti hai utna chhoti hoti hai?",
    "એક કોયડો ઉકેલો: 3 બિલાડીઓ 3 ઉંદર 3 મિનિટમાં પકડે, તો 100 ઉંદર 100 મિનિટમાં પકડવા કેટલી બિલાડી જોઈએ?",
    # --- sequences ---
    "What comes next in the series 2, 6, 12, 20, 30, ?",
    "Find the missing number: 3, 9, 27, __, 243",
    "अगली संख्या बताइए: 1, 4, 9, 16, ?",
    # --- code debugging / tracing ---
    "Why does this print 10 ten times instead of 0 to 9?\n```js\nfor (var i = 0; i < 10; i++) { setTimeout(() => console.log(i), 0); }\n```",
    "My function returns None, what's wrong?\n```python\ndef add(a, b):\n    result = a + b\nprint(add(2, 3))\n```",
    "What will this code output?\n```python\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(len(x))\n```",
    "Traceback (most recent call last):\n  File \"app.py\", line 12, in <module>\n    total = sum(items) / len(items)\nZeroDivisionError: division by zero\nhow do I fix this",
    "This binary search goes into an infinite loop, can you find the bug?\n\ndef search(a, t):\n    lo, hi = 0, len(a)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if a[mid] < t:\n            lo = mid\n        else:\n            hi = mid\n    return lo",
    "yeh code kyu nahi chal raha?\n```python\nnums = [3, 1, 2]\nsorted_nums = nums.sort()\nprint(sorted_nums[0])\n```",
    "Trace through this loop and tell me the final value of s:\ns = 0\nfor i in range(1, 6):\n    if i % 2 == 0:\n        s += i * i\n    else:\n        s -= i",
    "What is the time complexity of this function?\ndef f(n):\n    i = 1\n    while i < n:\n        i *= 2\n        for j in range(i):\n            pass",
]

MUST_NOT = [
    # --- greetings / chit-chat ---
    "hi",
    "Hello! How are you today?",
    "good morning",
    "thanks, that was helpful",
    "namaste",
    "kem cho?",
    "kaise ho bhai",
    "who are you?",
    "what can you do?",
    "tell me a fun fact",
    "I'm bored, talk to me",
    "Do you like music?",
    "ok bye",
    "नमस्ते, आप कैसे हैं?",
    "કેમ છો, મજામાં?",
    # --- factual lookups with numbers that need no reasoning ---
    "what is 5G",
    "top 10 movies 2024",
    "GST rate on mobile phones in India",
    "iPhone 15 price in India",
    "iPhone 15 vs iPhone 16 which is better",
    "What is the capital of Australia?",
    "How many states are there in India?",
    "India me kitne rajya hain?",
    "भारत में कितने राज्य हैं?",
    "ગુજરાતમાં કેટલા જિલ્લા છે?",
    "Who won the 2011 cricket world cup?",
    "When did World War 2 end?",
    "What is the boiling point of water?",
    "How tall is Mount Everest?",
    "How many bones are in the human body?",
    "What is COVID-19?",
    "What does GPT-4 stand for?",
    "Windows 11 system requirements",
    "Best 5 phones under 20000",
    "What is the population of Mumbai in 2024?",
    "Section 80C deduction limit",
    "What is the speed of light?",
    "How many players are in a football team?",
    "Class 12 board exam date 2025",
    "Who is the prime minister of India?",
    "What is the golden ratio?",
    "What is a Sharpe ratio?",
    "PS5 release date",
    "What is 2+2?",
    "7 times 8",
    "How far is the moon from Earth?",
    "Galaxy S24 camera specs",
    "What is the full form of NASA?",
    "Mahabharat me kitne parv hain?",
    "Taj Mahal kab bana tha?",
    # --- live values ---
    "dollar to rupee rate today",
    "What is the price of gold today in Ahmedabad?",
    "100 USD in INR",
    "Sensex today",
    "weather in Surat tomorrow",
    "IND vs AUS score",
    "Bitcoin price right now",
    "petrol ka rate kya hai aaj",
    "आज सोने का भाव क्या है?",
    "આજે ડોલરનો ભાવ શું છે?",
    # --- summaries ---
    "Summarize this: The company reported revenue of 4.5 billion in Q3, up 12% from last year, while operating costs rose 8% to 3.1 billion. The board approved a dividend of 2 per share.",
    "Give me a summary of the Ramayana in 5 points",
    "tl;dr of the article about electric vehicles",
    "Summarise the key points of chapter 3",
    "इस लेख का सारांश बताइए",
    # --- translations ---
    "Translate to Hindi: If a train travels 60 km in 1 hour, how far will it go in 3 hours?",
    "Translate 'good night, sleep well' into Gujarati",
    "translate karo: mujhe kal 10 baje office jaana hai",
    "इस वाक्य का अंग्रेज़ी में अनुवाद करें: मैं 5 बजे आऊंगा",
    "આ વાક્યનું અંગ્રેજીમાં ભાષાંતર કરો: હું સવારે 7 વાગ્યે ઉઠું છું",
    # --- writing tasks ---
    "Write a poem about the monsoon",
    "Draft an email to my manager asking for 2 days leave on 12 and 13 March",
    "Write a LinkedIn post about completing 5 years at my company",
    "Write a birthday wish for my sister turning 21",
    "Write a cover letter for a data analyst job",
    "Write a python function to reverse a string",
    "Create a SQL query to get the top 5 customers by revenue",
    "Write a short story about a robot and a cat",
    "mere dost ke liye shaadi ki badhai ka message likh do",
    "मेरे बॉस के लिए छुट्टी का आवेदन लिखिए",
    "મારા મિત્ર માટે જન્મદિવસની શુભેચ્છા લખો",
    "Rewrite this sentence more formally: we gonna be late by 10 mins",
    "Give me 10 Instagram captions for a beach trip",
    "Write a 300 word essay on pollution",
    # --- explanations / how-to without multi-step reasoning ---
    "Explain photosynthesis in simple words",
    "What is the difference between RAM and ROM?",
    "How do I install Python on Windows 11?",
    "How to make masala chai?",
    "What is machine learning?",
    "Why is the sky blue?",
    "Explain how a credit card works",
    "What are the benefits of yoga?",
    "How do I reset my Gmail password?",
    "What is the difference between a list and a tuple in Python?",
    "Recommend 3 books on personal finance",
    "Suggest a 7 day itinerary for Kerala",
    "What should I eat after a workout?",
    "Kal mera interview hai, kuch tips do",
    "Mujhe weight loss ke liye diet plan chahiye",
    "Python sikhne ke liye best resources kya hain?",
    "गर्मियों में त्वचा की देखभाल कैसे करें?",
    "ગુજરાતી થાળીમાં શું શું હોય છે?",
    "How do vaccines work?",
    "What is the meaning of life?",
    "Can you explain what an API is?",
    "Meeting at 5:30 pm tomorrow, remind me what to prepare for a product demo",
    "My phone number is 98765-43210, what should I write in a profile bio?",
    "Tell me about the 1:1 meeting best practices",
    "What happened on 15/08/1947?",
    "List the 12 zodiac signs",
    "Explain the 80/20 rule",
    "What is a 401k?",
    "Name 3 rivers in Gujarat",
    "What is a for loop in Python?",
]

#: Two further batches written AFTER the classifier had been tuned on the lists
#: above, and scored blind first (2026-09-15). Batch one: 10/20 must-think,
#: 0/40 false positives. Batch two, scored after tuning on batch one: 10/15,
#: 1/40 ("proof-of-work"). The classifier was then tuned on both, so these are
#: no longer held out — they are kept so the gates cover them. The two
#: remaining misses are real limits of a lexicon (a box-relabelling riddle with
#: no puzzle word, and "explain step by step how to convert 0.375").
HELD_OUT_MUST_THINK = [
    'A father is 4 times as old as his son. In 20 years he will be twice as old. How old is the son?',
    'If 3 pencils cost 45 rupees, how much do 8 pencils cost?',
    'A rectangle has perimeter 36 cm and length twice its width. Find its area.',
    'How many zeros are at the end of 100 factorial?',
    'A man walks 4 km north, 3 km east. How far is he from the start?',
    'I have two bottles, one 750 ml and one 500 ml. How do I measure 250 ml exactly?',
    'Mix 2 parts juice with 3 parts soda to make 1.5 litres. How much juice?',
    'Ek dukandar 20% munafa kamata hai, agar cost price 800 hai to selling price kitna hoga?',
    '5 aadmi ek kaam 12 din me karte hain, 3 aadmi kitne din me karenge?',
    'एक आयत की लंबाई 12 सेमी और चौड़ाई 8 सेमी है, उसका क्षेत्रफल और परिमाप ज्ञात कीजिए।',
    'એક દુકાનદાર 15% વળતર આપે છે. 2000 રૂપિયાની વસ્તુ માટે કેટલું ચૂકવવું પડે?',
    'Why does this SQL return duplicate rows?\nSELECT o.id, c.name FROM orders o JOIN customers c ON c.region = o.region;',
    "My React counter doesn't update:\nconst [n, setN] = useState(0);\nfunction inc() { n = n + 1; }\nwhat's the bug",
    'Is 221 a prime number? Show the reasoning.',
    'What is the sum of all integers from 1 to 200 that are divisible by 3 or 5?',
    'There are 3 boxes labelled apples, oranges, mixed, all labels wrong. Pick one fruit from one box — how do you relabel them all?',
    'If today is Wednesday, what day will it be 100 days from now?',
    'A clock loses 5 minutes every hour. If set right at noon, what time will it show at 6 pm?',
    'Prove that n^3 - n is divisible by 6 for every integer n.',
    'Why exactly is 0.999... equal to 1?',
    'Three consecutive even numbers add up to 78. What are they?',
    'A water tank leaks 2 litres per hour and a tap adds 5 litres per hour. Starting empty, when does it hold 60 litres?',
    'Agar 4 kitaabein 360 rupaye ki hain, to 7 kitaabein kitne ki hongi?',
    'Ek bottle me 2 bhaag garam aur 5 bhaag thanda paani milana hai bina naap ke, kaise karu?',
    'એક વર્ગમાં 40 વિદ્યાર્થીઓ છે, તેમાંથી 60% છોકરીઓ છે. છોકરા કેટલા છે?',
    'यदि 6 मजदूर एक दीवार 10 दिन में बनाते हैं, तो 15 मजदूर कितने दिन में बनाएंगे?',
    'What does this print?\n```python\ndef f(x=[]):\n    x.append(1)\n    return x\nf(); print(f())\n```',
    'Explain step by step how to convert 0.375 to a fraction.',
    'Is 1001 divisible by 7? Explain.',
    'A ladder 10 m long leans against a wall with its foot 6 m from the wall. How high up does it reach?',
    'How many ways can 4 people sit around a round table?',
    'Two coins are tossed. What is the probability of getting exactly one head?',
    'Solve: 5(x - 2) = 3x + 4',
    'Which is larger, 2^30 or 10^9? Show your working.',
    'My loop never ends, why?\nwhile i < 10:\n    print(i)',
]

HELD_OUT_MUST_NOT = [
    'What is the 5th amendment?',
    'who won IPL 2023',
    'Top 5 places to visit in Goa',
    'Samsung Galaxy S23 vs S24 camera',
    'what is 4G LTE',
    'How many calories in 2 boiled eggs?',
    'Distance between Ahmedabad and Mumbai',
    'What time is it in London?',
    'Book a table for 4 at 8 pm',
    'Is 2024 a leap year?',
    'How many days in February 2024?',
    'Jio 299 plan details',
    'What is RBI repo rate 2025?',
    'How much does a Tesla Model 3 cost?',
    "Explain Newton's 3 laws of motion",
    '10 tips for better sleep',
    'Write a function that adds two numbers',
    'Convert 5 km to miles',
    'Convert 100 fahrenheit to celsius',
    'What is the 2nd law of thermodynamics?',
    'Summarize: the train left at 9:15 and reached at 11:45, 30 minutes late due to fog.',
    'Translate: A shopkeeper sold 5 apples for 50 rupees.',
    'Write an email: our meeting at 3:30 pm is moved to 4:00 pm on 12/09',
    'Aaj ka match kitne baje hai?',
    'iPhone 16 kitne ka hai?',
    'मुझे 2 दिन की छुट्टी चाहिए, आवेदन कैसे लिखें?',
    'ગુજરાતની વસ્તી કેટલી છે 2024 માં?',
    'Which is bigger, the Pacific or the Atlantic?',
    'What are the side effects of paracetamol 650?',
    'Give me a 30 minute home workout',
    'How long does it take to learn Spanish?',
    "What's the ratio of men to women in India?",
    'Mix of 3 songs for a party playlist',
    'I scored 85 out of 100, is that good?',
    'Rs 500 ka recharge me kya milta hai?',
    'Remind me to drink water every 2 hours',
    'What does error 404 mean?',
    'What is a TypeError in Python?',
    'Recipe for 2 people pasta',
    'What is 10% of the population of Earth approximately?',
    'How long is the flight from Delhi to Mumbai?',
    'How much is 1 USD in INR and 1 EUR in INR?',
    'What is the difference between 4G and 5G?',
    'How many runs did Kohli score in the 2019 and 2023 World Cups?',
    'I have 2 kids aged 5 and 8, suggest weekend activities',
    'Plan a 3 day trip to Udaipur for 2 people',
    'What should a 30 year old with 50,000 salary invest in?',
    'Tell me 5 facts about the number 7',
    'Give me a diet plan for 1500 calories',
    'Find a good restaurant near me for 4 people',
    "Calculate my BMI? I don't know my weight",
    'My laptop has 8 GB RAM and 512 GB SSD, is it good for gaming?',
    'Compare the 2 plans: 399 and 599',
    'What happens if I take 2 paracetamol 500 tablets?',
    'Why is my phone battery draining fast?',
    'Why is Python so popular?',
    'Fix grammar: me and him goes to school at 8',
    "Explain the error 'module not found' in Node",
    'Can you explain what a function is in programming?',
    'How many hours should a 10 year old sleep?',
    'Write a story where 3 friends find 100 gold coins',
    'Kya 2 din me Goa ghum sakte hain?',
    '10 minute me pasta kaise banaye?',
    '5 saal ke bachche ke liye best books',
    'मुझे 3 महीने में वजन कम करना है, क्या करूँ?',
    'મને 2 દિવસમાં સોમનાથ ફરવાની યોજના બનાવી આપો',
    'Ahmedabad se Surat kitne km hai?',
    'Mere phone me 128 GB storage hai, kitne photos aa sakte hain approx?',
    'How many episodes in season 2 of The Last of Us?',
    "What's the score after 20 overs?",
    'Is it safe to run 5 km every day?',
    'List 10 tips for a job interview',
    'What is the difference between a mixture and a compound?',
    'How much water should I drink per day?',
    'What is the time complexity of binary search?',
    'Explain the proof-of-work concept in Bitcoin',
    'How do I measure my waist size?',
    'Which bottle is best for keeping water cold?',
    '3 idiots movie review',
    'Room 101 meaning',
]
