"""App-state PostgreSQL store (V2-DESIGN §3c): users, conversations, messages.

PostgreSQL since 2026-08-10; this module used to be stdlib `sqlite3` against
`/data/app.sqlite3`. This is APP state only — the DuckDB/LanceDB-only rule
still applies to the ANALYTICS data plane, and DuckDB is deliberately NOT
migrated: it is a columnar engine and beats PostgreSQL at the scan-and-
aggregate queries the SQL engine writes.

WHAT THE MOVE ACTUALLY BOUGHT, measured on this box against the live database
(378 messages) — including where it costs rather than saves, because most of
the obvious claims do not survive a benchmark:

  * WRITES: `add_message` 8.5 ms -> 2.8 ms, on the critical path of every chat
    turn. Real, but read the baseline carefully before believing the ratio.
    The SQLite code set `journal_mode=WAL` and never set `synchronous`, so it
    ran at the default FULL: one fsync per commit, measured here as 3.48 ms of
    a 3.49 ms write — literally 100% of the cost. At EQUAL durability the two
    engines are close (SQLite FULL 3.5 ms vs PostgreSQL `synchronous_commit=on`
    2.8 ms). Drop durability on either side and SQLite wins by a mile
    (`synchronous=NORMAL` is 0.010 ms; `synchronous_commit=off` is ~0.4 ms).
    So: this is a win over the code as it was, not evidence that PostgreSQL
    writes faster.
  * CONCURRENCY: this is the durable win. SQLite serialises writers behind a
    5 s busy timeout, and two tabs finalising the same answer surfaced that as
    an HTTP 500. MVCC removes the failure mode outright, and it is why the
    write path can now be offloaded to a threadpool at all.
  * PER-OPERATION OVERHEAD: `connect()` ran 15 `CREATE … IF NOT EXISTS`
    statements plus the whole `migrate()` path — including an unconditional
    full-table DELETE — on every one of its 34 call sites. That is gone. But a
    pooled checkout is 0.07-0.27 ms against SQLite's 0.24 ms of replay, so this
    nets out roughly even; the real gain is that an O(messages) DELETE no
    longer runs on every single database operation.
  * SMALL READS: 0.26 ms -> 0.37 ms, i.e. slightly SLOWER. An in-process file
    read has no round trip to beat. Both are far below anything perceivable.
  * SEARCH: it depends on the needle, and the honest summary is "no better at
    this size". Measured at 200,000 messages / 10,000 conversations: a
    selective term is 2.5 ms here versus ~19 ms for SQLite's linear scan, but a
    term matching most rows is 80 ms here versus 19 ms — trigram indexes cannot
    help when everything matches. At the live 378 messages SQLite is 2-6x
    faster on every search shape. See `_SEARCH_SQL` and `recall_conversations`.

In short: this migration is worth it for concurrency, real types, and a schema
that no longer rebuilds itself on every query — not for raw single-user speed
at the current data size.

WHAT DID NOT CHANGE: every public function keeps its name, signature and
return shape, so the ~24 call sites and the test-suite seams are untouched.
Rows are `dict` (psycopg's `dict_row`), which supports `row["col"]` and
`dict(row)` exactly as `sqlite3.Row` did. Timestamps are stored as
`timestamptz` but still leave this module as the same ISO-8601 strings the
frontend has always parsed.

Nothing here touches the database at import time.
"""
from __future__ import annotations

import functools
import json
import threading
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any, Callable, Dict, Iterator, List, Optional, Tuple, TypeVar

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb
from psycopg_pool import ConnectionPool

from .config import settings

# Driver-neutral aliases so callers never import psycopg. `history.py` and
# `auth.py` catch db.IntegrityError; swapping drivers again would only touch
# these three lines.
Error = psycopg.Error
IntegrityError = psycopg.errors.IntegrityError
UniqueViolation = psycopg.errors.UniqueViolation
OperationalError = psycopg.OperationalError

# ---------------------------------------------------------------------------
# Schema — versioned migrations, applied once at startup (see init_schema).
#
# The old policy was "additive ALTER only, evaluated on every connection".
# The additive-only *intent* is unchanged and matters more than ever now that
# the live database holds the owner's real conversations; what changed is that
# a numbered, recorded migration cannot silently re-run a destructive repair
# the way the old `migrate()` re-ran its de-duplicating DELETE forever.
# ---------------------------------------------------------------------------

_MIGRATION_V1 = """
-- Trigram indexes are what make the history search sub-linear; without this
-- extension every LIKE '%needle%' is a sequential scan, exactly as in SQLite.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS users (
    id            integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      text        NOT NULL,
    password_hash text        NOT NULL,
    created_at    timestamptz NOT NULL
);
-- SQLite spelled this `UNIQUE COLLATE NOCASE`. PostgreSQL's equivalent is a
-- unique index on the folded value: `citext` is discouraged upstream (it is a
-- deterministic-collation hack that breaks on some ICU locales) and a
-- non-deterministic collation would disable pattern matching on the column.
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_key ON users (lower(username));

CREATE TABLE IF NOT EXISTS conversations (
    id         text        PRIMARY KEY,   -- client-supplied
    user_id    integer     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title      text        NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    pinned     boolean     NOT NULL DEFAULT false,
    archived   boolean     NOT NULL DEFAULT false,
    -- Insertion order. SQLite got this free from `rowid`, which the sidebar
    -- ordering used as its final tiebreak; PostgreSQL has no such column, and
    -- without one two conversations created in the same microsecond sort
    -- non-deterministically between page loads.
    seq        bigint      GENERATED BY DEFAULT AS IDENTITY
);
CREATE INDEX IF NOT EXISTS idx_conversations_user
    ON conversations (user_id, pinned DESC, updated_at DESC, seq DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_title_trgm
    ON conversations USING gin (title gin_trgm_ops);

CREATE TABLE IF NOT EXISTS messages (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id text        NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role            text        NOT NULL,
    content         text        NOT NULL,
    -- jsonb, not text: psycopg adapts dict <-> jsonb directly, which deletes
    -- the json.dumps/json.loads pair this column used to need.
    meta            jsonb,
    created_at      timestamptz NOT NULL,
    -- Idempotency key for one model generation. Several clients can be
    -- attached to the same detached generation (a second browser joining a
    -- running answer); each would otherwise persist its own copy of the same
    -- reply. Appends carrying a generation_id already present in the
    -- conversation are no-ops.
    generation_id   text
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages (conversation_id, id);
-- One message per generation, enforced in the DATABASE. Two browser tabs
-- attached to the same detached answer append at the same moment, so an
-- application-level "select then insert" check loses the race.
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_generation
    ON messages (conversation_id, generation_id) WHERE generation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_content_trgm
    ON messages USING gin (content gin_trgm_ops);

-- Phase A: one rolling summary per conversation. Its own table, not a column
-- on `conversations`, so writing a summary never touches the row the sidebar
-- orders by (updated_at).
CREATE TABLE IF NOT EXISTS conversation_summaries (
    conversation_id text        PRIMARY KEY REFERENCES conversations(id) ON DELETE CASCADE,
    summary         text        NOT NULL,
    -- COUNT of leading messages already folded in. A count (not a row id)
    -- because a request's turns arrive from the client, which has no server
    -- ids; it makes folding idempotent — only messages beyond it are ever
    -- folded, so a crash mid-compact can neither double-fold nor skip.
    covers_through  integer     NOT NULL,
    token_estimate  integer     NOT NULL,
    updated_at      timestamptz NOT NULL
);

-- Phase B: embedded chunks of FOLDED turns, so detail the summary dropped can
-- still be retrieved. Scoped per conversation — the WHERE clause is what
-- enforces session isolation.
CREATE TABLE IF NOT EXISTS conversation_chunks (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id text        NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    ordinal         bigint      NOT NULL,
    role            text        NOT NULL,
    text            text        NOT NULL,
    -- bytea, holding the same packed float32 bytes recall.py already writes.
    -- Deliberately NOT pgvector: the only read path is a brute-force cosine
    -- over ONE conversation's chunks, which is microseconds, so an ANN index
    -- would add an extension dependency for nothing.
    embedding       bytea       NOT NULL,
    created_at      timestamptz NOT NULL,
    UNIQUE (conversation_id, ordinal)
);

-- Phase 4: uploaded datasets. The PROFILE lives here, not the bytes, so a
-- conversation keeps answering questions after the workspace TTL has swept
-- the extracted files away.
CREATE TABLE IF NOT EXISTS uploads (
    id              text        PRIMARY KEY,
    conversation_id text        NOT NULL,
    filename        text        NOT NULL,
    bytes           bigint      NOT NULL,
    status          text        NOT NULL,
    profile         jsonb,
    notes           text,
    created_at      timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_uploads_conversation ON uploads (conversation_id, created_at);

-- Phase 2: pages fetched for a conversation, so follow-up questions about the
-- same URL are answered from stored content without re-fetching.
CREATE TABLE IF NOT EXISTS url_documents (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id text        NOT NULL,
    url             text        NOT NULL,
    title           text        NOT NULL,
    text            text        NOT NULL,
    fetched_at      timestamptz NOT NULL,
    UNIQUE (conversation_id, url)
);
CREATE INDEX IF NOT EXISTS idx_url_documents_conv ON url_documents (conversation_id, id);

-- 2026-08-07: full text of uploaded documents (PDF/DOCX/plain), stored per
-- conversation so EVERY later turn can reference them — the file itself was
-- only ever sent on the turn it was attached, and the model forgot it after.
CREATE TABLE IF NOT EXISTS documents (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id text        NOT NULL,
    filename        text        NOT NULL,
    text            text        NOT NULL,
    total_pages     integer     NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL,
    UNIQUE (conversation_id, filename)
);
CREATE INDEX IF NOT EXISTS idx_documents_conv ON documents (conversation_id, id);

-- Phase 3: cloned+indexed GitHub repos and their code chunks (per conversation).
CREATE TABLE IF NOT EXISTS repos (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id text        NOT NULL,
    repo_key        text        NOT NULL,
    url             text        NOT NULL,
    sha             text        NOT NULL,
    cloned_at       timestamptz NOT NULL,
    UNIQUE (conversation_id, repo_key)
);
CREATE TABLE IF NOT EXISTS repo_chunks (
    id              bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id text    NOT NULL,
    repo_key        text    NOT NULL,
    path            text    NOT NULL,
    start_line      integer NOT NULL,
    end_line        integer NOT NULL,
    text            text    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_repo_chunks_conv ON repo_chunks (conversation_id, repo_key, id);
CREATE INDEX IF NOT EXISTS idx_repo_chunks_text_trgm ON repo_chunks USING gin (text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_repo_chunks_path_trgm ON repo_chunks USING gin (path gin_trgm_ops);
"""

_MIGRATION_V2 = """
-- Measured on the live database after a day of use (pg_stat_user_indexes):
--
--   idx_messages_content_trgm      798 scans   2872 kB   <- earns its keep
--   idx_repo_chunks_text_trgm        0 scans   7608 kB
--   idx_repo_chunks_path_trgm        0 scans   1136 kB
--   idx_conversations_title_trgm     0 scans    112 kB
--
-- The three unused ones were speculative. search_repo_chunks always filters
-- `conversation_id = ?` first, which is far more selective than any trigram
-- match, so the planner takes idx_repo_chunks_conv and never looks at them —
-- while a repo index writes thousands of rows through COPY in one go, and a
-- GIN index bigger than the table it covers makes that materially slower.
-- The title index loses to a sequential scan of a table this narrow.
DROP INDEX IF EXISTS idx_repo_chunks_text_trgm;
DROP INDEX IF EXISTS idx_repo_chunks_path_trgm;
DROP INDEX IF EXISTS idx_conversations_title_trgm;

-- The sidebar's query is `WHERE user_id = ? AND archived = ?`, but `archived`
-- was not in the index, so EXPLAIN showed `Index Cond: (user_id = 1)` followed
-- by `Filter: (NOT archived)` — every one of the user's conversations read and
-- then discarded. Putting `archived` second makes it an index condition.
-- Only one index, deliberately: `updated_at` is bumped on every appended
-- message, so each extra index containing it is paid for on every turn.
DROP INDEX IF EXISTS idx_conversations_user;
CREATE INDEX IF NOT EXISTS idx_conversations_user
    ON conversations (user_id, archived, pinned DESC, updated_at DESC, seq DESC);
"""

_MIGRATION_V3 = """
-- Per-message thumbs (owner request 2026-08-11). Lives ON the message rather
-- than in a side table: there is one user, no audit requirement, and "with the
-- chat" is exactly what was asked for — so it cascades with the conversation,
-- comes back in the same SELECT the thread already does, and cannot drift out
-- of sync with the message it describes.
--
-- Until now this was localStorage only, which had a bug nobody had noticed:
-- the browser keys feedback by a client-side message id, and a message
-- rehydrated from the server is keyed positionally instead
-- (`srv-<conversation>-<index>`), so a thumb given to a fresh reply was LOST
-- on the next reload. Making the server the source of truth fixes that.
--
-- NULL means "no opinion" — the common case, and cheap: a nullable text column
-- costs nothing per row until it is set.
ALTER TABLE messages ADD COLUMN IF NOT EXISTS feedback text;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS feedback_at timestamptz;

-- The constraint is the point: without it a typo'd client could write "thumbs
-- up", "1" or "" and every consumer would need to defend against it.
ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_feedback_check;
ALTER TABLE messages ADD CONSTRAINT messages_feedback_check
    CHECK (feedback IS NULL OR feedback IN ('up', 'down'));

-- Partial: only the handful of rated messages are indexed, so "show me
-- everything I disliked" stays fast without taxing every INSERT.
CREATE INDEX IF NOT EXISTS idx_messages_feedback
    ON messages (conversation_id, id) WHERE feedback IS NOT NULL;
"""

_MIGRATION_V4 = """
-- Where a conversation's title came from (2026-08-11, AI titles).
--   'auto'      — derived from the first message; may be replaced by the model
--   'generated' — the model named it; do not regenerate
--   'user'      — the owner renamed it; NEVER touch it again
--
-- This column IS the rename guard. Without it, auto-titling is a
-- read-then-write race: a rename landing between the read and the write would
-- be silently reverted, and the user would watch their own title change back.
-- With it the guarded UPDATE is one atomic statement and the rename wins
-- deterministically, no lock required.
--
-- Existing rows default to 'auto', which is honest — every title in the
-- database today came from `titleFromFirstMessage` — and leaves them eligible
-- for the backfill script.
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS title_source text NOT NULL DEFAULT 'auto';

ALTER TABLE conversations DROP CONSTRAINT IF EXISTS conversations_title_source_check;
ALTER TABLE conversations ADD CONSTRAINT conversations_title_source_check
    CHECK (title_source IN ('auto', 'generated', 'user'));
"""

_MIGRATION_V5 = """
-- Salesforce Intelligence Mode (2026-08-11): the pending request being
-- resolved, the one question we are asking about it, and what this
-- conversation has established about Salesforce so far.
--
-- WHY IN THE DATABASE AND NOT IN MEMORY: a clarification card has to survive a
-- browser reload, a second tab, a reconnect, and an orchestrator restart. The
-- detached-generation buffer (LiveGeneration in main.py) is per-process and
-- dies with the answer it was streaming, so it cannot hold a question that is
-- waiting on a human.
--
-- `conversation_id` is a plain column with NO foreign key, exactly like
-- `uploads`/`documents`/`repos` above: POST /chat supports a bare API call with
-- no `conversations` row at all, and a foreign key would turn "this chat asked a
-- clarifying question" into a failed request for those callers.
-- `delete_conversation` clears these three tables explicitly, in the same
-- transaction, so nothing is orphaned.

CREATE TABLE IF NOT EXISTS sf_intents (
    intent_id       text        PRIMARY KEY,
    conversation_id text        NOT NULL,
    status          text        NOT NULL,
    -- The whole PendingIntent, validated by pydantic on the way in and out.
    -- One jsonb column rather than a dozen typed ones: the shape belongs to
    -- app/core/sf_intel/models.py, and mirroring it in DDL would mean a
    -- migration every time a slot is added.
    payload         jsonb       NOT NULL,
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sf_intents_conversation
    ON sf_intents (conversation_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS sf_clarifications (
    clarification_id text        PRIMARY KEY,
    conversation_id  text        NOT NULL,
    intent_id        text        NOT NULL,
    -- pending | answered | skipped | cancelled
    state            text        NOT NULL,
    -- Server-generated opaque value the client must present to resume. Stored,
    -- not derived, so rotating it is a single UPDATE and a stale card in an old
    -- tab cannot resume an intent that has since been replaced.
    resume_token     text        NOT NULL,
    question_fingerprint text    NOT NULL,
    payload          jsonb       NOT NULL,
    response         jsonb,
    -- The client's idempotency key for the click that answered this. A second
    -- submission (a double-click, a retried fetch) finds the row already
    -- resolved and gets the FIRST answer back instead of starting a second run.
    client_message_id text,
    created_at       timestamptz NOT NULL,
    resolved_at      timestamptz
);
-- At most ONE pending clarification per conversation, enforced in the DATABASE.
-- Two sends racing (the composer and a stale tab) would otherwise both insert,
-- and the user would see two cards for one request.
CREATE UNIQUE INDEX IF NOT EXISTS idx_sf_clarifications_one_pending
    ON sf_clarifications (conversation_id) WHERE state = 'pending';
CREATE INDEX IF NOT EXISTS idx_sf_clarifications_intent
    ON sf_clarifications (intent_id, created_at);

CREATE TABLE IF NOT EXISTS sf_conversation_state (
    conversation_id text        PRIMARY KEY,
    payload         jsonb       NOT NULL,
    updated_at      timestamptz NOT NULL
);
"""

#: (version, DDL). Append only; never edit a version that has shipped.
#:
#: NOTE on `uploads`, `url_documents`, `documents`, `repos` and `repo_chunks`:
#: these keep `conversation_id` as a plain column with NO foreign key, exactly
#: as under SQLite — deliberately. `/chat` supports a bare API call that has no
#: `conversations` row at all (`conv_key = conversation_id or session_id`,
#: main.py), and a foreign key would turn "this chat fetched a URL" into a
#: failed answer for those callers. DATA-03 — the permanent orphaning of that
#: content when a conversation is deleted — is fixed in `delete_conversation`,
#: which now removes the side rows explicitly in the same transaction.
_MIGRATIONS: tuple = (
    (1, _MIGRATION_V1),
    (2, _MIGRATION_V2),
    (3, _MIGRATION_V3),
    (4, _MIGRATION_V4),
    (5, _MIGRATION_V5),
)

#: The version `init_schema` brings a database up to. Exported so callers (and
#: tests) can assert "fully migrated" without hardcoding a number that has to be
#: edited every time a migration is appended — which is exactly how a schema
#: assertion stops being a check and becomes a chore.
LATEST_SCHEMA_VERSION: int = max(version for version, _ddl in _MIGRATIONS)

_MIGRATION_TABLE = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version    integer     PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);
"""

#: Any 64-bit constant; it only has to be stable and not collide with another
#: advisory lock in this database. Two orchestrators starting together take it
#: in turn instead of racing to CREATE the same index.
_MIGRATION_LOCK_KEY = 0x5346_4149_4442


# ---------------------------------------------------------------------------
# Connection pool
# ---------------------------------------------------------------------------

_pool: Optional[ConnectionPool] = None
_pool_lock = threading.Lock()
_pool_dsn: Optional[str] = None


def _server_options() -> str:
    """libpq `options`, applied to every connection the pool opens.

    - `timezone=UTC` is load-bearing, not hygiene: a `timestamptz` renders in
      the session time zone, and every timestamp this module returns is
      `datetime.isoformat()`. Any other zone would silently change the strings
      the frontend and the tests have always seen.
    - `statement_timeout` is the bound SQLite never had; an unbounded query
      used to hold a request open indefinitely.
    - `idle_in_transaction_session_timeout` stops a leaked transaction from
      pinning a pooled connection (and holding back vacuum) forever.
    """
    return (
        "-c timezone=UTC"
        f" -c statement_timeout={int(settings.app_db_statement_timeout_ms)}"
        " -c idle_in_transaction_session_timeout=60000"
    )


def dsn() -> str:
    """The configured DSN, or a loud failure.

    No localhost default on purpose: a silent fallback is how a deploy ends up
    writing history into a database nobody can find.
    """
    configured = (settings.app_database_url or "").strip()
    if not configured:
        raise RuntimeError(
            "APP_DATABASE_URL is not set — the app-state database is PostgreSQL "
            "since 2026-08-10. Example: "
            "postgresql://techsara:<password>@postgres:5432/techsara"
        )
    return configured


def pool() -> ConnectionPool:
    """The process-wide connection pool, opened on first use.

    Rebuilt when `settings.app_database_url` changes, which is what lets the
    test suite point each test at its own database.
    """
    global _pool, _pool_dsn
    wanted = dsn()
    if _pool is not None and _pool_dsn == wanted and not _pool.closed:
        return _pool
    with _pool_lock:
        if _pool is not None and _pool_dsn == wanted and not _pool.closed:
            return _pool
        if _pool is not None:
            _close_pool_locked()
        created = ConnectionPool(
            conninfo=wanted,
            min_size=max(0, int(settings.app_db_pool_min)),
            max_size=max(1, int(settings.app_db_pool_max)),
            timeout=float(settings.app_db_pool_timeout),
            # A pooled connection outlives the server it was opened against.
            # Without a liveness check the first request after a `docker
            # compose restart postgres` fails; with it, the pool quietly
            # replaces the dead connection.
            check=ConnectionPool.check_connection,
            kwargs={
                "row_factory": dict_row,
                "autocommit": False,
                "options": _server_options(),
            },
            name="app-state",
            open=False,
        )
        created.open(wait=True, timeout=float(settings.app_db_pool_timeout))
        _pool, _pool_dsn = created, wanted
        return _pool


def _close_pool_locked() -> None:
    global _pool, _pool_dsn
    if _pool is not None:
        try:
            _pool.close()
        except Exception:  # noqa: BLE001 — shutdown must not raise
            pass
    _pool, _pool_dsn = None, None


def close_pool() -> None:
    """Release every pooled connection (app shutdown, and between tests)."""
    with _pool_lock:
        _close_pool_locked()


@contextmanager
def connection() -> Iterator[psycopg.Connection]:
    """A pooled connection wrapped in one transaction.

    Commits on a clean exit, rolls back on an exception, and returns the
    connection to the pool either way — the direct replacement for the old
    `with closing(connect()) as con, con:` idiom, minus the 0.24 ms of schema
    replay that used to precede it.
    """
    with pool().connection() as con:
        yield con


T = TypeVar("T")


async def run_in_thread(fn: Callable[..., T], *args: Any, **kwargs: Any) -> T:
    """Await a blocking accessor from `async def` without stalling the loop.

    Every function in this module is synchronous by design: `history.py`'s
    routes are plain `def` and FastAPI already runs those in the threadpool,
    and making the module async would have coloured all 39 functions plus
    every test. The handful of genuinely async callers (`main.py`,
    `compaction.py`, the engines) use this instead — one `await` per call site
    rather than a rewrite, and the event loop stays free to pump the other
    in-flight SSE streams.
    """
    import anyio  # local: keeps this module importable without a running loop

    return await anyio.to_thread.run_sync(functools.partial(fn, *args, **kwargs))


# ---------------------------------------------------------------------------
# Schema application
# ---------------------------------------------------------------------------


def wait_for_database(timeout: Optional[float] = None) -> None:
    """Block until PostgreSQL accepts a connection, or give up after `timeout`.

    THIS EXISTS FOR REBOOTS. `depends_on: service_healthy` only orders
    `docker compose up`; when the Docker daemon brings containers back after a
    power cut it starts them all at once and honours no such ordering. Without
    this, the orchestrator raced PostgreSQL, failed its lifespan, exited, and
    was restarted by `restart: unless-stopped` — measured at 8 crash-restarts
    in one simulated power cut. It always recovered, but Docker's restart
    backoff grows with each failure, so on a real boot (five vLLM services
    competing for the same disk) recovery is delayed by exactly the time the
    machine is busiest.

    Waiting instead of dying keeps ONE container start, a readable log line
    while it waits, and recovery the moment the database is ready.

    It still gives up eventually: a DSN pointing at a database that will never
    exist is a deploy error, and it should be loud rather than a container that
    hangs "starting" forever. Exceeding the deadline raises, the process exits,
    and Docker restarts it — so even then it self-heals, just noisily.
    """
    import logging
    import time

    deadline = time.monotonic() + (
        float(settings.app_db_startup_timeout) if timeout is None else timeout
    )
    log = logging.getLogger(__name__)
    target = dsn().rsplit("@", 1)[-1]  # never log the password
    attempt = 0
    while True:
        attempt += 1
        try:
            with psycopg.connect(dsn(), connect_timeout=5) as con:
                con.execute("SELECT 1")
            if attempt > 1:
                log.warning(
                    "postgres at %s is up (after %d attempts)", target, attempt
                )
            return
        except psycopg.OperationalError as exc:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise RuntimeError(
                    f"postgres at {target} did not accept a connection within "
                    f"{settings.app_db_startup_timeout:.0f}s ({attempt} attempts). "
                    f"Last error: {exc}"
                ) from exc
            # Back off gently, capped, so a slow boot does not spin the CPU and
            # a fast one still gets going within a second.
            time.sleep(min(3.0, 0.25 * attempt, max(0.1, remaining)))
            if attempt in (1, 5) or attempt % 20 == 0:
                log.warning(
                    "waiting for postgres at %s (attempt %d, %.0fs left): %s",
                    target, attempt, remaining, str(exc).strip().splitlines()[0],
                )


def init_schema() -> None:
    """Apply any unapplied migrations. Idempotent; safe to call concurrently.

    Called once from the FastAPI lifespan so a broken migration fails the
    deploy rather than the first request that happens to touch the database.
    `pg_advisory_xact_lock` serialises two instances starting together, and
    releases automatically when the transaction ends — including on failure,
    where PostgreSQL's transactional DDL also rolls the partial schema back.
    """
    with connection() as con:
        with con.transaction():
            con.execute("SELECT pg_advisory_xact_lock(%s)", (_MIGRATION_LOCK_KEY,))
            con.execute(_MIGRATION_TABLE)
            applied = {
                int(row["version"])
                for row in con.execute("SELECT version FROM schema_migrations").fetchall()
            }
            for version, ddl in _MIGRATIONS:
                if version in applied:
                    continue
                con.execute(ddl)
                con.execute(
                    "INSERT INTO schema_migrations (version) VALUES (%s)", (version,)
                )


def schema_version() -> int:
    """Highest applied migration version, or 0 on an empty database."""
    with connection() as con:
        row = con.execute(
            "SELECT COALESCE(MAX(version), 0) AS v FROM schema_migrations"
        ).fetchone()
    return int(row["v"]) if row else 0


# ---------------------------------------------------------------------------
# Row helpers
# ---------------------------------------------------------------------------


def _now() -> datetime:
    return datetime.now(timezone.utc)


def utcnow() -> str:
    """ISO-8601 UTC, the string shape this app has always emitted."""
    return _now().isoformat()


def _iso(value: Any) -> Any:
    """`timestamptz` -> the same ISO-8601 string SQLite stored verbatim.

    The session runs in UTC (see `_server_options`), so this reproduces
    `datetime.now(timezone.utc).isoformat()` exactly, offset included.
    """
    return value.isoformat() if isinstance(value, datetime) else value


def _row(row: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """Row -> plain JSON-friendly dict (timestamps become ISO strings)."""
    if row is None:
        return None
    return {key: _iso(value) for key, value in row.items()}


def _text(value: Optional[str]) -> Optional[str]:
    """Strip NUL characters, which PostgreSQL `text` cannot store.

    SQLite accepted `\\x00` inside a TEXT value; PostgreSQL rejects it outright
    ("unsupported Unicode escape sequence" / "invalid byte sequence"). Almost
    everything written here is untrusted text — model output, extracted PDF and
    OCR transcripts, scraped pages, source files — and any one of those can
    carry a stray NUL. Without this, a single bad byte turns a completed answer
    into a 500 and loses it.

    The membership test keeps the common path allocation-free; documents can be
    several MB and copying every one of them to remove nothing would be waste.
    """
    if value is None or "\x00" not in value:
        return value
    return value.replace("\x00", "")


def _dumps_jsonb(obj: Any) -> str:
    """`json.dumps` for jsonb: tolerant of odd types, free of NUL escapes.

    `default=str` mirrors the old call — `meta` carries whatever the engines put
    in it, and a stray datetime must not turn a stored answer into a 500.
    `json.dumps` always escapes NUL as the six characters `\\u0000`, which jsonb
    rejects, so the escape is removed from the serialised form.
    """
    text = json.dumps(obj, ensure_ascii=False, default=str)
    return text.replace("\\u0000", "") if "\\u0000" in text else text


def _json_param(value: Optional[Any]) -> Optional[Jsonb]:
    """Adapt a dict — or a pre-serialised JSON string — to a jsonb parameter."""
    if value is None:
        return None
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except (TypeError, ValueError):
            # Not JSON after all — keep it addressable rather than dropping it.
            value = {"raw": value}
    return Jsonb(value, dumps=_dumps_jsonb)


# ---------------------------------------------------------------------------
# Users
# ---------------------------------------------------------------------------


def create_user(username: str, password_hash: str) -> int:
    """Insert a user; raises db.IntegrityError on a duplicate username
    (unique on lower(username) — SQLite's COLLATE NOCASE)."""
    with connection() as con:
        row = con.execute(
            "INSERT INTO users (username, password_hash, created_at) "
            "VALUES (%s, %s, %s) RETURNING id",
            (_text(username), password_hash, _now()),
        ).fetchone()
    return int(row["id"])


def get_user_by_username(username: str) -> Optional[Dict[str, Any]]:
    with connection() as con:
        row = con.execute(
            "SELECT * FROM users WHERE lower(username) = lower(%s)", (username,)
        ).fetchone()
    return _row(row)


def get_user_by_id(user_id: int) -> Optional[Dict[str, Any]]:
    with connection() as con:
        row = con.execute("SELECT * FROM users WHERE id = %s", (user_id,)).fetchone()
    return _row(row)


def oldest_user() -> Optional[Dict[str, Any]]:
    """The first account ever created — the one whose history to adopt.

    Lives here rather than in `auth.py` so nothing outside this module has to
    open a connection of its own (the old `auth._oldest_user` opened one and
    never closed it, leaking a handle per resolution).
    """
    with connection() as con:
        row = con.execute("SELECT * FROM users ORDER BY id LIMIT 1").fetchone()
    return _row(row)


# ---------------------------------------------------------------------------
# Conversations + messages — every accessor is scoped to a user_id (§3c):
# a conversation owned by someone else is indistinguishable from a missing
# one (the caller turns None/False into 404).
# ---------------------------------------------------------------------------


def _conversation_dict(row: Dict[str, Any]) -> dict:
    """Row → JSON-friendly dict. The flags are real booleans now; the coercion
    stays so a caller that stored 0/1 through some other path still reads back
    `true`/`false` in the API."""
    out = _row(row) or {}
    for flag in ("pinned", "archived"):
        if flag in out:
            out[flag] = bool(out[flag])
    return out


def list_conversations(user_id: int, archived: bool = False) -> List[dict]:
    """The user's conversations, active by default (V3-DESIGN §1).

    `archived=True` returns the archived ones instead — the two sets are
    disjoint, so the sidebar's Archived section is a separate fetch. Pinned
    conversations float to the top, then most-recent activity.
    """
    with connection() as con:
        rows = con.execute(
            "SELECT id, title, updated_at, pinned, archived FROM conversations "
            "WHERE user_id = %s AND archived = %s "
            "ORDER BY pinned DESC, updated_at DESC, seq DESC",
            (user_id, bool(archived)),
        ).fetchall()
    return [_conversation_dict(r) for r in rows]


def create_conversation(user_id: int, conversation_id: str, title: str) -> dict:
    """Insert a conversation; raises db.IntegrityError when the id exists."""
    now = _now()
    with connection() as con:
        con.execute(
            "INSERT INTO conversations (id, user_id, title, created_at, updated_at) "
            "VALUES (%s, %s, %s, %s, %s)",
            (conversation_id, user_id, _text(title), now, now),
        )
    return {
        "id": conversation_id,
        "title": title,
        "created_at": now.isoformat(),
        "updated_at": now.isoformat(),
        "pinned": False,
        "archived": False,
    }


def get_conversation(user_id: int, conversation_id: str) -> Optional[dict]:
    with connection() as con:
        row = con.execute(
            "SELECT id, title, created_at, updated_at, pinned, archived "
            "FROM conversations WHERE id = %s AND user_id = %s",
            (conversation_id, user_id),
        ).fetchone()
    return _conversation_dict(row) if row else None


def update_conversation(
    user_id: int,
    conversation_id: str,
    title: Optional[str] = None,
    pinned: Optional[bool] = None,
    archived: Optional[bool] = None,
) -> Optional[dict]:
    """Update any subset of {title, pinned, archived}; None means "leave alone".

    Only a rename counts as activity: pinning or archiving sets the flag and
    nothing else, so a chat keeps its place in the updated_at ordering when it
    comes back out of the archive (V3-DESIGN §1). Returns None when the
    conversation is missing or owned by someone else.
    """
    assignments: List[str] = []
    values: List[object] = []
    if title is not None:
        # A rename is an act of ownership: mark the title 'user' so the
        # auto-titler can never overwrite it, on this device or any other.
        assignments += ["title = %s", "title_source = 'user'", "updated_at = %s"]
        values += [_text(title), _now()]
    if pinned is not None:
        assignments.append("pinned = %s")
        values.append(bool(pinned))
    if archived is not None:
        assignments.append("archived = %s")
        values.append(bool(archived))
    if not assignments:  # nothing to change — just an ownership-scoped read
        return get_conversation(user_id, conversation_id)
    with connection() as con:
        # RETURNING makes this one round trip instead of an UPDATE followed by
        # a SELECT, and closes the window where another tab could change the
        # row between the two.
        row = con.execute(
            f"UPDATE conversations SET {', '.join(assignments)} "
            "WHERE id = %s AND user_id = %s "
            "RETURNING id, title, created_at, updated_at, pinned, archived",
            (*values, conversation_id, user_id),
        ).fetchone()
    return _conversation_dict(row) if row else None


#: Conversation-keyed tables with no foreign key (see the note on _MIGRATIONS).
#: Deleting a conversation has to clear these by hand.
_SIDE_TABLES = (
    "uploads",
    "url_documents",
    "documents",
    "repos",
    "repo_chunks",
    # Salesforce Intelligence Mode. A deleted conversation must not leave a
    # pending clarification behind: the unique partial index below allows one
    # per conversation, so an orphan would block the id from ever being reused.
    "sf_clarifications",
    "sf_intents",
    "sf_conversation_state",
)


def set_generated_title(user_id: int, conversation_id: str, title: str) -> Optional[dict]:
    """Write an AI-generated title, but ONLY over an auto-derived one.

    `title_source = 'auto'` in the WHERE clause is the entire rename guard, and
    it is inside the statement rather than around it on purpose: a
    check-then-write leaves a window where a rename lands between the two and
    is silently reverted — the user watching their own title flip back. Here a
    rename simply makes this UPDATE match zero rows.

    Returns the updated row, or None when the title is already 'user' or
    'generated', the conversation is missing, or it belongs to someone else.
    Callers treat None as "leave it alone", never as an error.
    """
    with connection() as con:
        row = con.execute(
            "UPDATE conversations SET title = %s, title_source = 'generated' "
            " WHERE id = %s AND user_id = %s AND title_source = 'auto' "
            "RETURNING id, title, title_source",
            (_text(title), conversation_id, user_id),
        ).fetchone()
    return _row(row) if row else None


def conversation_title_state(user_id: int, conversation_id: str) -> Optional[dict]:
    """{title, title_source} for one conversation, or None when not theirs.

    Lets a caller skip the model for a conversation that is already named —
    the cheapest LLM call is the one never made.
    """
    with connection() as con:
        row = con.execute(
            "SELECT title, title_source FROM conversations "
            "WHERE id = %s AND user_id = %s",
            (conversation_id, user_id),
        ).fetchone()
    return _row(row) if row else None


def delete_conversation(user_id: int, conversation_id: str) -> bool:
    """Delete a conversation and everything keyed to it.

    Fixes DATA-03. Under SQLite this issued exactly one statement, and only
    `messages`, `conversation_summaries` and `conversation_chunks` had a
    cascading foreign key — so a delete permanently orphaned the conversation's
    uploads, fetched page text, cloned-repo records and every code chunk. That
    is the largest content in the database and nothing could ever reach it
    again. The side tables are cleared explicitly here, in the same
    transaction, so the delete is all-or-nothing.

    Ownership is still checked in the same statement that deletes, so a
    conversation belonging to someone else is a no-op returning False — and
    the side-table deletes only run once that check has passed.
    """
    with connection() as con:
        cur = con.execute(
            "DELETE FROM conversations WHERE id = %s AND user_id = %s",
            (conversation_id, user_id),
        )
        if cur.rowcount == 0:
            return False
        for table in _SIDE_TABLES:
            con.execute(
                f"DELETE FROM {table} WHERE conversation_id = %s", (conversation_id,)
            )
        return True


def list_messages(conversation_id: str) -> List[dict]:
    """The thread, oldest first.

    `id` is included so the client has a STABLE server-side identity for each
    message. It had none before: a live message is keyed by a browser-minted
    uuid and a rehydrated one positionally as `srv-<conversation>-<index>`, so
    anything attached to a message client-side (thumbs) was lost on reload.
    """
    with connection() as con:
        rows = con.execute(
            "SELECT id, role, content, meta, feedback FROM messages "
            "WHERE conversation_id = %s ORDER BY id",
            (conversation_id,),
        ).fetchall()
    # `meta` arrives already parsed — it is jsonb, not a JSON string.
    return [
        {
            "id": int(r["id"]),
            "role": r["role"],
            "content": r["content"],
            "meta": r["meta"],
            "feedback": r["feedback"],
        }
        for r in rows
    ]


#: The only values `messages.feedback` accepts (mirrored by a CHECK constraint).
FEEDBACK_VALUES = ("up", "down")


def set_message_feedback(
    user_id: int, conversation_id: str, message_id: int, feedback: Optional[str]
) -> Optional[dict]:
    """Record (or clear, with None) a thumb on one message.

    Returns the updated {id, feedback, feedback_at}, or None when the message
    does not exist, is not in that conversation, or the conversation belongs to
    someone else — the same "missing and forbidden are indistinguishable" rule
    every other accessor here follows, so a caller cannot probe for ids.

    Ownership is enforced in the STATEMENT, not by a check-then-write: a
    separate lookup would be a race, and this way a message in another
    account's conversation simply matches no row.
    """
    if feedback is not None and feedback not in FEEDBACK_VALUES:
        raise ValueError(f"feedback must be one of {FEEDBACK_VALUES} or None")
    with connection() as con:
        row = con.execute(
            "UPDATE messages m SET feedback = %s, feedback_at = %s "
            "  FROM conversations c "
            " WHERE m.conversation_id = c.id "
            "   AND m.id = %s AND m.conversation_id = %s AND c.user_id = %s "
            "RETURNING m.id, m.feedback, m.feedback_at",
            (
                feedback,
                _now() if feedback is not None else None,
                message_id,
                conversation_id,
                user_id,
            ),
        ).fetchone()
    if row is None:
        return None
    return {
        "id": int(row["id"]),
        "feedback": row["feedback"],
        "feedback_at": _iso(row["feedback_at"]),
    }


def list_confirmed_sql_examples(limit: int = 200) -> List[dict]:
    """(question, sql) pairs a user confirmed with a thumbs-up, newest first.

    The learning loop (core/learned_examples.py) replays these as few-shot
    examples when a similar question arrives. Two safety rules live in the
    query itself:
      * only assistant messages whose meta actually carries the executed SQL
        count — a thumb on a prose answer teaches nothing about SQL;
      * any SQL text that ALSO received a thumbs-down anywhere is excluded
        outright. A query one user liked and another flagged is contested,
        and a contested example is worse than none.
    The question is the nearest earlier user turn in the same conversation —
    messages are keyed by position because offline sync rewrites their ids
    (see replace_messages).
    """
    with connection() as con:
        rows = con.execute(
            """
            WITH rated AS (
                SELECT m.id, m.conversation_id, m.meta->>'sql' AS sql
                  FROM messages m
                 WHERE m.feedback = 'up' AND m.role = 'assistant'
                   AND m.meta->>'sql' IS NOT NULL
                 ORDER BY m.feedback_at DESC NULLS LAST
                 LIMIT %s
            )
            SELECT r.sql,
                   (SELECT q.content FROM messages q
                     WHERE q.conversation_id = r.conversation_id
                       AND q.id < r.id AND q.role = 'user'
                     ORDER BY q.id DESC LIMIT 1) AS question
              FROM rated r
             WHERE NOT EXISTS (
                    SELECT 1 FROM messages b
                     WHERE b.feedback = 'down'
                       AND b.meta->>'sql' = r.sql
                   )
            """,
            (limit,),
        ).fetchall()
    examples = []
    for row in rows:
        question = (row["question"] or "").strip()
        sql = (row["sql"] or "").strip()
        if question and sql:
            examples.append({"question": question, "sql": sql})
    return examples


def conversation_owner(conversation_id: str) -> Optional[int]:
    """user_id owning this conversation, or None when no such row exists.

    Used to authorize the per-conversation stores (url_documents, repo_chunks,
    live generations) that are keyed by conversation id alone.
    """
    with connection() as con:
        row = con.execute(
            "SELECT user_id FROM conversations WHERE id = %s", (conversation_id,)
        ).fetchone()
    return int(row["user_id"]) if row else None


class MessageCountWouldShrink(Exception):
    """A sync tried to replace a thread with a SHORTER one.

    The client's offline sync used to reconcile a diverged tail by deleting
    the conversation and recreating it from its local copy. When that local
    copy was empty or stale (a chat listed by the server but never opened in
    this browser, or one evicted by a localStorage quota purge) the rebuild
    destroyed every earlier turn. Shrinking is never a legitimate sync
    outcome — only an explicit DELETE of the whole conversation is.
    """

    def __init__(self, existing: int, incoming: int) -> None:
        super().__init__(f"refusing to replace {existing} messages with {incoming}")
        self.existing = existing
        self.incoming = incoming


# ---------------------------------------------------------------------------
# Phase A/B: rolling summary + folded-turn chunks
# ---------------------------------------------------------------------------


def get_summary(conversation_id: str) -> Optional[dict]:
    with connection() as con:
        row = con.execute(
            "SELECT summary, covers_through, token_estimate, updated_at "
            "FROM conversation_summaries WHERE conversation_id = %s",
            (conversation_id,),
        ).fetchone()
    if row is None:
        return None
    return {
        "summary": row["summary"],
        "covers_through": int(row["covers_through"]),
        "token_estimate": int(row["token_estimate"]),
        "updated_at": _iso(row["updated_at"]),
    }


def save_summary(
    conversation_id: str, summary: str, covers_through: int, token_estimate: int
) -> None:
    with connection() as con:
        con.execute(
            "INSERT INTO conversation_summaries "
            "(conversation_id, summary, covers_through, token_estimate, updated_at) "
            "VALUES (%s, %s, %s, %s, %s) "
            "ON CONFLICT (conversation_id) DO UPDATE SET "
            "summary = excluded.summary, covers_through = excluded.covers_through, "
            "token_estimate = excluded.token_estimate, updated_at = excluded.updated_at",
            (conversation_id, _text(summary), covers_through, token_estimate, _now()),
        )


def clear_summary(conversation_id: str) -> None:
    """Drop the summary and folded chunks for a conversation.

    Used when the thread is truncated (a confirmed regenerate of an older
    answer): the summary describes turns that no longer exist, so keeping it
    would let the model assert things the user deliberately removed.
    """
    with connection() as con:
        con.execute(
            "DELETE FROM conversation_summaries WHERE conversation_id = %s",
            (conversation_id,),
        )
        con.execute(
            "DELETE FROM conversation_chunks WHERE conversation_id = %s",
            (conversation_id,),
        )


def add_conversation_chunks(conversation_id: str, chunks: List[dict]) -> None:
    """Store embedded chunks of folded turns (ordinal = index in the thread)."""
    if not chunks:
        return
    now = _now()
    with connection() as con:
        con.cursor().executemany(
            "INSERT INTO conversation_chunks "
            "(conversation_id, ordinal, role, text, embedding, created_at) "
            "VALUES (%s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (conversation_id, ordinal) DO UPDATE SET "
            "role = excluded.role, text = excluded.text, "
            "embedding = excluded.embedding, created_at = excluded.created_at",
            [
                (
                    conversation_id,
                    int(c["ordinal"]),
                    _text(c["role"]),
                    _text(c["text"]),
                    c["embedding"],
                    now,
                )
                for c in chunks
            ],
        )


def get_conversation_chunks(conversation_id: str) -> List[dict]:
    """Every folded chunk for ONE conversation — the isolation boundary."""
    with connection() as con:
        rows = con.execute(
            "SELECT ordinal, role, text, embedding FROM conversation_chunks "
            "WHERE conversation_id = %s ORDER BY ordinal",
            (conversation_id,),
        ).fetchall()
    return [
        {
            "ordinal": int(r["ordinal"]),
            "role": r["role"],
            "text": r["text"],
            # bytea comes back as `memoryview`; recall.unpack_vector wants
            # something array.frombytes accepts, and callers may hold it past
            # the cursor, so materialise it.
            "embedding": bytes(r["embedding"]),
        }
        for r in rows
    ]


# ---------------------------------------------------------------------------
# Phase 4: uploaded datasets (profile stored, bytes expire separately)
# ---------------------------------------------------------------------------


def save_upload(
    upload_id: str,
    conversation_id: str,
    filename: str,
    size: int,
    status: str,
    profile: Optional[str] = None,
    notes: Optional[str] = None,
) -> None:
    with connection() as con:
        con.execute(
            "INSERT INTO uploads (id, conversation_id, filename, bytes, status, "
            "profile, notes, created_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (id) DO UPDATE SET status = excluded.status, "
            "profile = excluded.profile, notes = excluded.notes",
            (
                upload_id,
                conversation_id,
                _text(filename),
                size,
                status,
                _json_param(profile),
                _text(notes),
                _now(),
            ),
        )


def get_uploads(conversation_id: str) -> List[dict]:
    """Uploads for ONE conversation — the isolation boundary."""
    with connection() as con:
        rows = con.execute(
            "SELECT id, filename, bytes, status, profile, notes, created_at "
            "FROM uploads WHERE conversation_id = %s ORDER BY created_at",
            (conversation_id,),
        ).fetchall()
    return [
        {
            "id": r["id"],
            "filename": r["filename"],
            "bytes": int(r["bytes"]),
            "status": r["status"],
            "profile": r["profile"],
            "notes": r["notes"],
            "created_at": _iso(r["created_at"]),
        }
        for r in rows
    ]


def get_upload(upload_id: str) -> Optional[dict]:
    with connection() as con:
        row = con.execute(
            "SELECT id, conversation_id, filename, bytes, status, profile, notes "
            "FROM uploads WHERE id = %s",
            (upload_id,),
        ).fetchone()
    if row is None:
        return None
    return {
        "id": row["id"],
        "conversation_id": row["conversation_id"],
        "filename": row["filename"],
        "bytes": int(row["bytes"]),
        "status": row["status"],
        "profile": row["profile"],
        "notes": row["notes"],
    }


class ConversationChanged(Exception):
    """The stored thread is not the one the caller was looking at."""

    def __init__(self, expected: int, actual: int) -> None:
        super().__init__(f"expected {expected} messages, found {actual}")
        self.expected = expected
        self.actual = actual


def truncate_messages(
    user_id: int, conversation_id: str, keep: int, expected_total: int
) -> Optional[dict]:
    """Drop every message after the first `keep` — the ONE sanctioned shrink.

    This exists so a user-confirmed "regenerate an older answer" (which really
    does discard the turns after that point) does not need the sync path to be
    able to shrink. The separation is the safety property: the sync path can
    never reduce a thread, and this endpoint can only ever delete a tail — it
    cannot write content, so a bug here cannot rewrite history, only shorten
    it, and only when the caller proves it knows the current length.

    `expected_total` is optimistic concurrency: if another tab appended turns
    since the caller last looked, this raises instead of destroying them.

    FOR UPDATE on the owning row is new: SQLite's single-writer lock made the
    count-then-delete atomic for free, and MVCC does not. Without it two
    concurrent truncates can both read the same count and both pass the check.
    """
    with connection() as con:
        owned = con.execute(
            "SELECT 1 FROM conversations WHERE id = %s AND user_id = %s FOR UPDATE",
            (conversation_id, user_id),
        ).fetchone()
        if not owned:
            return None
        actual = int(
            con.execute(
                "SELECT COUNT(*) AS n FROM messages WHERE conversation_id = %s",
                (conversation_id,),
            ).fetchone()["n"]
        )
        if actual != expected_total:
            raise ConversationChanged(expected_total, actual)
        if keep >= actual:
            return {"id": conversation_id, "count": actual}
        # Find the id of the last message to KEEP, then range-delete past it.
        # The SQLite original used `id NOT IN (SELECT … LIMIT keep)`, which
        # PostgreSQL also accepts — but that re-scans every surviving row,
        # while this does one index probe and a range delete whose cost scales
        # with the rows actually removed. `keep == 0` has no boundary row, so
        # it deletes the lot.
        boundary = None
        if keep > 0:
            row = con.execute(
                "SELECT id FROM messages WHERE conversation_id = %s "
                "ORDER BY id OFFSET %s LIMIT 1",
                (conversation_id, keep - 1),
            ).fetchone()
            boundary = row["id"] if row else None
        if boundary is None:
            con.execute(
                "DELETE FROM messages WHERE conversation_id = %s", (conversation_id,)
            )
        else:
            con.execute(
                "DELETE FROM messages WHERE conversation_id = %s AND id > %s",
                (conversation_id, boundary),
            )
        con.execute(
            "UPDATE conversations SET updated_at = %s WHERE id = %s",
            (_now(), conversation_id),
        )
    return {"id": conversation_id, "count": keep}


def replace_messages(
    user_id: int, conversation_id: str, messages: List[dict]
) -> Optional[dict]:
    """Atomically replace a conversation's messages, never reducing the count.

    Returns None when the conversation is missing or owned by someone else,
    and raises MessageCountWouldShrink when the incoming thread is shorter
    than what is stored. The delete+insert runs in ONE transaction, so a
    failure cannot leave the conversation empty.

    FEEDBACK SURVIVES. This is a DELETE followed by an INSERT, so every row
    gets a new id — which would silently discard the thumbs on a thread the
    client happens to re-push (the offline sync does exactly that whenever the
    tail diverges). Thumbs are carried across BY POSITION, which is sound here
    precisely because of the guarantee above: this function can never reorder
    or shrink a thread, only append to it, so index N before is index N after.
    An explicit `feedback` on an incoming message wins over the carried value.
    """
    now = _now()
    with connection() as con:
        owned = con.execute(
            "SELECT 1 FROM conversations WHERE id = %s AND user_id = %s FOR UPDATE",
            (conversation_id, user_id),
        ).fetchone()
        if not owned:
            return None
        existing = int(
            con.execute(
                "SELECT COUNT(*) AS n FROM messages WHERE conversation_id = %s",
                (conversation_id,),
            ).fetchone()["n"]
        )
        if len(messages) < existing:
            raise MessageCountWouldShrink(existing, len(messages))
        # Snapshot the thumbs before the rows they belong to are deleted.
        carried = [
            r["feedback"]
            for r in con.execute(
                "SELECT feedback FROM messages WHERE conversation_id = %s ORDER BY id",
                (conversation_id,),
            ).fetchall()
        ]
        con.execute("DELETE FROM messages WHERE conversation_id = %s", (conversation_id,))
        seen_generations = set()
        rows = []
        for index, m in enumerate(messages):
            meta = m.get("meta")
            gen_id = (meta or {}).get("generation_id")
            # The unique index would reject a repeated key; a client sending
            # one twice is a bug on its side, not a reason to 500 — keep the
            # first and store the rest unkeyed.
            if gen_id:
                if gen_id in seen_generations:
                    gen_id = None
                else:
                    seen_generations.add(gen_id)
            feedback = m.get("feedback")
            if feedback not in FEEDBACK_VALUES:
                # Not supplied (or junk) — keep whatever was on this position.
                feedback = carried[index] if index < len(carried) else None
            rows.append(
                (
                    conversation_id,
                    _text(m.get("role", "")),
                    _text(m.get("content", "")),
                    _json_param(meta),
                    now,
                    str(gen_id) if gen_id else None,
                    feedback,
                    now if feedback else None,
                )
            )
        if rows:
            con.cursor().executemany(
                "INSERT INTO messages (conversation_id, role, content, meta, created_at, "
                "generation_id, feedback, feedback_at) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
                rows,
            )
        con.execute(
            "UPDATE conversations SET updated_at = %s WHERE id = %s",
            (now, conversation_id),
        )
    return {"id": conversation_id, "count": len(messages)}


def add_message(
    user_id: int,
    conversation_id: str,
    role: str,
    content: str,
    meta: Optional[dict] = None,
) -> Optional[dict]:
    """Append a message to a conversation the user owns; bumps updated_at.

    Returns None when the conversation is missing or owned by someone else.

    IDEMPOTENT per generation: when `meta.generation_id` is present and a
    message from that same generation already exists here, the existing row is
    returned untouched. Two clients attached to one detached generation (a
    second browser opening a running answer) both finalize and both push —
    without this the same reply is stored twice.
    """
    now = _now()
    generation_id = (meta or {}).get("generation_id")
    with connection() as con:
        owned = con.execute(
            "SELECT 1 FROM conversations WHERE id = %s AND user_id = %s",
            (conversation_id, user_id),
        ).fetchone()
        if not owned:
            return None

        # PostgreSQL aborts the whole transaction on a constraint violation, so
        # the SQLite shape (try INSERT / except IntegrityError / SELECT the
        # winner on the same connection) cannot work here — the follow-up
        # SELECT would fail with "current transaction is aborted". A SAVEPOINT
        # scopes the rollback to the INSERT alone.
        inserted = None
        try:
            with con.transaction():
                inserted = con.execute(
                    "INSERT INTO messages (conversation_id, role, content, meta, "
                    "created_at, generation_id) VALUES (%s, %s, %s, %s, %s, %s) "
                    "RETURNING id",
                    (
                        conversation_id,
                        _text(role),
                        _text(content),
                        _json_param(meta),
                        now,
                        str(generation_id) if generation_id else None,
                    ),
                ).fetchone()
        except UniqueViolation:
            # The unique index rejected it: another client stored this exact
            # generation first. Hand back the row that won — no duplicate.
            if not generation_id:
                raise
            row = con.execute(
                "SELECT id, role, content, meta, created_at FROM messages "
                "WHERE conversation_id = %s AND generation_id = %s",
                (conversation_id, str(generation_id)),
            ).fetchone()
            if row is None:
                raise
            return {
                "id": int(row["id"]),
                "role": row["role"],
                "content": row["content"],
                "meta": row["meta"],
                "created_at": _iso(row["created_at"]),
                "deduplicated": True,
            }

        con.execute(
            "UPDATE conversations SET updated_at = %s WHERE id = %s",
            (now, conversation_id),
        )
        message_id = int(inserted["id"])
    return {
        "id": message_id,
        "role": role,
        "content": content,
        "meta": meta,
        "created_at": now.isoformat(),
    }


# ---------------------------------------------------------------------------
# Phase 2: fetched-page storage (per conversation, so follow-ups don't refetch)
# ---------------------------------------------------------------------------


def save_url_document(conversation_id: str, url: str, title: str, text: str) -> None:
    """Store (or refresh) an extracted page for a conversation."""
    with connection() as con:
        con.execute(
            "INSERT INTO url_documents (conversation_id, url, title, text, fetched_at) "
            "VALUES (%s, %s, %s, %s, %s) "
            "ON CONFLICT (conversation_id, url) DO UPDATE SET "
            "title = excluded.title, text = excluded.text, "
            "fetched_at = excluded.fetched_at",
            (conversation_id, _text(url), _text(title), _text(text), _now()),
        )


def get_url_documents(conversation_id: str) -> List[dict]:
    """All pages stored for a conversation, oldest first."""
    with connection() as con:
        rows = con.execute(
            "SELECT url, title, text FROM url_documents "
            "WHERE conversation_id = %s ORDER BY id",
            (conversation_id,),
        ).fetchall()
    return [{"url": r["url"], "title": r["title"], "text": r["text"]} for r in rows]


def get_url_document_urls(conversation_id: str) -> set:
    """The set of URLs already fetched for a conversation (dupe check)."""
    with connection() as con:
        rows = con.execute(
            "SELECT url FROM url_documents WHERE conversation_id = %s",
            (conversation_id,),
        ).fetchall()
    return {r["url"] for r in rows}


def save_document(
    conversation_id: str, filename: str, text: str, total_pages: int = 0
) -> None:
    """Store (or refresh) an uploaded document's extracted text."""
    with connection() as con:
        con.execute(
            "INSERT INTO documents (conversation_id, filename, text, total_pages, "
            "created_at) VALUES (%s, %s, %s, %s, %s) "
            "ON CONFLICT (conversation_id, filename) DO UPDATE SET "
            "text = excluded.text, total_pages = excluded.total_pages, "
            "created_at = excluded.created_at",
            (conversation_id, _text(filename), _text(text), total_pages, _now()),
        )


def get_documents(conversation_id: str) -> List[dict]:
    """All documents stored for a conversation, oldest first."""
    with connection() as con:
        rows = con.execute(
            "SELECT filename, text, total_pages FROM documents "
            "WHERE conversation_id = %s ORDER BY id",
            (conversation_id,),
        ).fetchall()
    return [
        {"filename": r["filename"], "text": r["text"], "total_pages": r["total_pages"]}
        for r in rows
    ]


# ---------------------------------------------------------------------------
# Phase 3: repo + code-chunk storage (per conversation)
# ---------------------------------------------------------------------------


def save_repo(conversation_id: str, repo_key: str, url: str, sha: str) -> None:
    with connection() as con:
        con.execute(
            "INSERT INTO repos (conversation_id, repo_key, url, sha, cloned_at) "
            "VALUES (%s, %s, %s, %s, %s) "
            "ON CONFLICT (conversation_id, repo_key) DO UPDATE SET "
            "url = excluded.url, sha = excluded.sha, cloned_at = excluded.cloned_at",
            (conversation_id, _text(repo_key), _text(url), _text(sha), _now()),
        )


def get_repo(conversation_id: str, repo_key: str) -> Optional[dict]:
    with connection() as con:
        row = con.execute(
            "SELECT repo_key, url, sha FROM repos "
            "WHERE conversation_id = %s AND repo_key = %s",
            (conversation_id, repo_key),
        ).fetchone()
    return dict(row) if row else None


def get_repo_keys(conversation_id: str) -> List[str]:
    with connection() as con:
        rows = con.execute(
            "SELECT repo_key FROM repos WHERE conversation_id = %s ORDER BY id",
            (conversation_id,),
        ).fetchall()
    return [r["repo_key"] for r in rows]


def replace_repo_chunks(
    conversation_id: str, repo_key: str, chunks: List[dict]
) -> None:
    """Store a repo's code chunks, replacing any previous set for that repo."""
    with connection() as con:
        con.execute(
            "DELETE FROM repo_chunks WHERE conversation_id = %s AND repo_key = %s",
            (conversation_id, repo_key),
        )
        if not chunks:
            return
        # COPY, not executemany: indexing a repo writes thousands of rows in one
        # go, and COPY streams them in a single statement instead of a round
        # trip apiece.
        with con.cursor().copy(
            "COPY repo_chunks (conversation_id, repo_key, path, start_line, end_line, "
            "text) FROM STDIN"
        ) as copy:
            for c in chunks:
                copy.write_row(
                    (
                        conversation_id,
                        repo_key,
                        _text(c["path"]),
                        c["start_line"],
                        c["end_line"],
                        _text(c["text"]),
                    )
                )


def search_repo_chunks(
    conversation_id: str, keywords: List[str], limit: int = 12
) -> List[dict]:
    """Code chunks in the conversation's repos matching any keyword, ranked by
    number of matching keywords (path matches weighted). Returns
    [{path, start_line, end_line, text}]."""
    if not keywords:
        return []
    patterns = [like_contains_pattern(k) for k in keywords]
    # score = matches in text + 2x matches in path (path names are strong signal)
    score_terms = " + ".join(
        "(CASE WHEN text ILIKE %s ESCAPE '\\' THEN 1 ELSE 0 END) + "
        "(CASE WHEN path ILIKE %s ESCAPE '\\' THEN 2 ELSE 0 END)"
        for _ in keywords
    )
    like_any = " OR ".join(
        "text ILIKE %s ESCAPE '\\' OR path ILIKE %s ESCAPE '\\'" for _ in keywords
    )
    # Doc files (README/HISTORY/…) often mention a term in prose; for "where is
    # X handled" the real source file should win, so penalize docs a little.
    doc_penalty = (
        "(CASE WHEN lower(path) LIKE '%%.md' OR lower(path) LIKE '%%.rst' "
        "OR lower(path) LIKE '%%.txt' OR lower(path) LIKE '%%.markdown' "
        "THEN 2 ELSE 0 END)"
    )
    sql = (
        f"SELECT path, start_line, end_line, text, "
        f"(({score_terms}) - {doc_penalty}) AS score "
        "FROM repo_chunks WHERE conversation_id = %s "
        f"AND ({like_any}) ORDER BY score DESC, id LIMIT %s"
    )
    # Bind in the ORDER the %s placeholders appear in the SQL text:
    # score_terms (SELECT) → conversation_id (WHERE) → like_any (AND) → limit.
    params: List[object] = []
    for p in patterns:
        params += [p, p]  # score_terms
    params.append(conversation_id)
    for p in patterns:
        params += [p, p]  # like_any
    params.append(limit)
    with connection() as con:
        rows = con.execute(sql, params).fetchall()
    return [
        {
            "path": r["path"],
            "start_line": r["start_line"],
            "end_line": r["end_line"],
            "text": r["text"],
        }
        for r in rows
    ]


# ---------------------------------------------------------------------------
# Search (V4-DESIGN §2) — one row per conversation, matched on the title or on
# any message body, scoped to the owner like every other accessor here.
# ---------------------------------------------------------------------------

SEARCH_LIMIT_DEFAULT = 50
SEARCH_LIMIT_MAX = 100  # hard cap: a bigger ?limit is clamped, never an error

_LIKE_ESCAPE = "\\"
_SNIPPET_WIDTH = 120
_ELLIPSIS = "…"


def like_contains_pattern(needle: str) -> str:
    """`needle` as a literal LIKE "contains" pattern.

    The user's text is data, not syntax: `%`, `_` and the escape character
    itself are escaped so searching for "50%" or "q_1" matches those literal
    characters instead of turning into a wildcard. Every statement using this
    pattern MUST pair it with the matching ESCAPE clause (see _SEARCH_SQL) —
    without one, PostgreSQL still treats `\\` as the default escape, but being
    explicit is what keeps the behaviour identical if that ever changes.
    """
    escaped = (
        needle.replace(_LIKE_ESCAPE, _LIKE_ESCAPE * 2)
        .replace("%", _LIKE_ESCAPE + "%")
        .replace("_", _LIKE_ESCAPE + "_")
    )
    return f"%{escaped}%"


def snippet_window(content: str, needle: str, width: int = _SNIPPET_WIDTH) -> str:
    """A ~`width`-character window of `content` centered on the first
    case-insensitive occurrence of `needle`.

    Short messages come back whole; a trimmed end gets an ellipsis so the
    palette can show that the message continues. When the hit sits near the
    tail the window is slid back so it stays `width` wide instead of running
    short. `needle` not being found is not an error (SQL's LIKE and Python's
    casefolding can disagree on exotic characters) — the head of the message is
    a reasonable snippet in that case.
    """
    if len(content) <= width:
        return content
    hit = content.lower().find(needle.lower())
    center = 0 if hit < 0 else hit + len(needle) // 2
    start = max(0, center - width // 2)
    end = min(len(content), start + width)
    start = max(0, end - width)  # re-widen when the hit sits near the tail
    snippet = content[start:end]
    if start > 0:
        snippet = _ELLIPSIS + snippet
    if end < len(content):
        snippet = snippet + _ELLIPSIS
    return snippet


# ILIKE, not LIKE. SQLite's LIKE is case-INSENSITIVE for ASCII, so a verbatim
# port silently stops matching anything capitalised — searching "merger" would
# miss a chat titled "Merger". The `gin_trgm_ops` indexes on `messages.content`
# and `conversations.title` serve ILIKE too, so this costs nothing.
# ESCAPE '\' is what makes like_contains_pattern's escaping real.
#
# The QUERY SHAPE is deliberately unchanged from the SQLite original — the
# correlated subquery that looks like it should be rewritten. It was rewritten,
# as a single-pass `DISTINCT ON` CTE, and then reverted, because the rewrite is
# only faster on a corpus small enough for the difference not to matter.
# Measured on 200,000 messages / 10,000 conversations:
#
#                        selective needle   needle matching everything
#   correlated (this)          2.5 ms                80 ms
#   DISTINCT ON CTE            7.8 ms                61 ms
#
# The correlated form wins 3x on the SELECTIVE case — a user searching their
# own history types a distinctive word. EXPLAIN shows why, and it is NOT
# short-circuiting: PostgreSQL de-correlates the EXISTS into a *hashed* SubPlan
# evaluated once against idx_messages_content_trgm. When that hash holds a
# handful of ids the outer walk discards almost everything cheaply and the
# per-row snippet subquery runs only for the survivors. The CTE instead has to
# materialise every match and SORT it for `DISTINCT ON` before it can return a
# single row, which only pays off when nearly everything matches. On the
# 378-message live database the two are within 1 ms, so the small-scale
# benchmark that motivated the rewrite was measuring noise.
#
# Archived conversations are deliberately NOT filtered out — they come back
# flagged so the palette can label them (§2).
_SEARCH_SQL = """
SELECT c.id, c.title, c.updated_at, c.pinned, c.archived,
       (SELECT m.content
          FROM messages m
         WHERE m.conversation_id = c.id
           AND m.content ILIKE %(pattern)s ESCAPE '\\'
         ORDER BY m.id
         LIMIT 1) AS match_content
  FROM conversations c
 WHERE c.user_id = %(user_id)s
   AND (c.title ILIKE %(pattern)s ESCAPE '\\'
        OR EXISTS (SELECT 1
                     FROM messages m2
                    WHERE m2.conversation_id = c.id
                      AND m2.content ILIKE %(pattern)s ESCAPE '\\'))
 ORDER BY c.pinned DESC, c.updated_at DESC, c.seq DESC
 LIMIT %(limit)s
"""


_RECALL_SNIPPET_CHARS = 240


def recall_conversations(
    user_id: int,
    keywords: List[str],
    exclude_conversation_id: Optional[str],
    limit: int = 3,
) -> List[dict]:
    """Cross-chat memory: the user's OTHER conversations whose messages mention
    any of `keywords`, ranked by how many messages match. Returns
    [{id, title, snippet}] — a compact recall context for the model. Scoped to
    the owner like every accessor here; the current conversation is excluded.

    One statement, not the old rank-then-snippet-per-row pair: LATERAL fetches
    each winner's snippet in the same pass, so this no longer issues N+1
    queries (it was 1 + `limit` round trips, each paying the old connect() tax).
    """
    if not keywords:
        return []
    patterns = [like_contains_pattern(k) for k in keywords]
    like_any = " OR ".join("m.content ILIKE %s ESCAPE '\\'" for _ in keywords)
    snippet_any = " OR ".join("s.content ILIKE %s ESCAPE '\\'" for _ in keywords)
    sql = (
        "WITH ranked AS ("
        "  SELECT c.id, c.title, c.updated_at, COUNT(m.id) AS hits"
        "    FROM conversations c JOIN messages m ON m.conversation_id = c.id"
        f"   WHERE c.user_id = %s AND c.id <> %s AND ({like_any})"
        "   GROUP BY c.id, c.title, c.updated_at"
        "   ORDER BY hits DESC, c.updated_at DESC"
        "   LIMIT %s"
        ") "
        "SELECT ranked.id, ranked.title, snip.content "
        "  FROM ranked "
        "  LEFT JOIN LATERAL ("
        "    SELECT s.content FROM messages s"
        f"    WHERE s.conversation_id = ranked.id AND ({snippet_any})"
        "     ORDER BY s.id LIMIT 1"
        "  ) AS snip ON true "
        " ORDER BY ranked.hits DESC, ranked.updated_at DESC"
    )
    params: List[object] = [user_id, exclude_conversation_id or "", *patterns, limit]
    params += patterns
    with connection() as con:
        rows = con.execute(sql, params).fetchall()
    out: List[dict] = []
    for r in rows:
        content = (r["content"] or "").strip().replace("\n", " ")
        if len(content) > _RECALL_SNIPPET_CHARS:
            content = content[:_RECALL_SNIPPET_CHARS] + "…"
        out.append({"id": r["id"], "title": r["title"], "snippet": content})
    return out


def search_conversations(
    user_id: int, query: str, limit: int = SEARCH_LIMIT_DEFAULT
) -> List[dict]:
    """The user's conversations matching `query` in the title or any message.

    Returns the documented row shape: {id, title, updated_at, pinned, archived,
    snippet, matched_in}. `matched_in` is "message" whenever some message body
    matched (the snippet then windows the FIRST such message) and "title" only
    when the title alone matched — so `snippet is None` exactly when
    `matched_in == "title"`, which is the invariant the palette renders on.
    """
    query = query.strip()
    if not query:  # empty/whitespace query is a no-op, not an error (§2)
        return []
    limit = max(1, min(int(limit), SEARCH_LIMIT_MAX))
    with connection() as con:
        rows = con.execute(
            _SEARCH_SQL,
            {
                "pattern": like_contains_pattern(query),
                "user_id": user_id,
                "limit": limit,
            },
        ).fetchall()
    out: List[dict] = []
    for row in rows:
        match_content = row["match_content"]
        out.append(
            {
                "id": row["id"],
                "title": row["title"],
                "updated_at": _iso(row["updated_at"]),
                "pinned": bool(row["pinned"]),
                "archived": bool(row["archived"]),
                "snippet": (
                    snippet_window(match_content, query)
                    if match_content is not None
                    else None
                ),
                "matched_in": "message" if match_content is not None else "title",
            }
        )
    return out


# ---------------------------------------------------------------------------
# Salesforce Intelligence Mode (migration 5)
#
# Three tables, one job: make a clarifying question survive everything that can
# happen between asking it and getting an answer — a reload, a second tab, a
# reconnect, an orchestrator restart. Payloads are stored whole as jsonb and
# validated by pydantic at the edges (app/core/sf_intel/state.py); this layer
# only moves rows and enforces the two invariants that MUST be atomic:
# one pending clarification per conversation, and first-response-wins.
# ---------------------------------------------------------------------------


def save_sf_intent(
    intent_id: str, conversation_id: str, status: str, payload: dict
) -> None:
    """Insert or update one pending intent."""
    now = _now()
    with connection() as con:
        con.execute(
            "INSERT INTO sf_intents "
            "(intent_id, conversation_id, status, payload, created_at, updated_at) "
            "VALUES (%s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (intent_id) DO UPDATE SET "
            "  status = EXCLUDED.status, payload = EXCLUDED.payload, "
            "  updated_at = EXCLUDED.updated_at",
            (intent_id, conversation_id, status, _json_param(payload), now, now),
        )


def get_sf_intent(intent_id: str) -> Optional[dict]:
    with connection() as con:
        row = con.execute(
            "SELECT intent_id, conversation_id, status, payload FROM sf_intents "
            "WHERE intent_id = %s",
            (intent_id,),
        ).fetchone()
    return _row(row) if row else None


def latest_open_sf_intent(conversation_id: str) -> Optional[dict]:
    """The most recent intent for this conversation that is not finished."""
    with connection() as con:
        row = con.execute(
            "SELECT intent_id, conversation_id, status, payload FROM sf_intents "
            "WHERE conversation_id = %s AND status IN ('open', 'awaiting_clarification') "
            "ORDER BY updated_at DESC LIMIT 1",
            (conversation_id,),
        ).fetchone()
    return _row(row) if row else None


def close_sf_intents(conversation_id: str, status: str = "cancelled") -> int:
    """Finish every open intent for a conversation. Returns how many."""
    with connection() as con:
        cur = con.execute(
            "UPDATE sf_intents SET status = %s, updated_at = %s "
            "WHERE conversation_id = %s AND status IN ('open', 'awaiting_clarification')",
            (status, _now(), conversation_id),
        )
        return cur.rowcount


def create_sf_clarification(
    *,
    clarification_id: str,
    conversation_id: str,
    intent_id: str,
    resume_token: str,
    question_fingerprint: str,
    payload: dict,
) -> bool:
    """Persist a pending clarification. False when one is already pending.

    The conflict target is the PARTIAL unique index, so this is the database
    enforcing "one open question per conversation" rather than a read-then-write
    that two racing sends both win.
    """
    with connection() as con:
        cur = con.execute(
            "INSERT INTO sf_clarifications "
            "(clarification_id, conversation_id, intent_id, state, resume_token, "
            " question_fingerprint, payload, created_at) "
            "VALUES (%s, %s, %s, 'pending', %s, %s, %s, %s) "
            "ON CONFLICT (conversation_id) WHERE state = 'pending' DO NOTHING",
            (
                clarification_id,
                conversation_id,
                intent_id,
                resume_token,
                question_fingerprint,
                _json_param(payload),
                _now(),
            ),
        )
        return cur.rowcount == 1


def _clarification_dict(row: Dict[str, Any]) -> dict:
    out = _row(row) or {}
    return {
        "clarification_id": out.get("clarification_id"),
        "conversation_id": out.get("conversation_id"),
        "intent_id": out.get("intent_id"),
        "state": out.get("state"),
        "resume_token": out.get("resume_token"),
        "question_fingerprint": out.get("question_fingerprint"),
        "payload": out.get("payload") or {},
        "response": out.get("response"),
        "client_message_id": out.get("client_message_id"),
        "created_at": _iso(out.get("created_at")),
        "resolved_at": _iso(out.get("resolved_at")),
    }


_CLARIFICATION_COLUMNS = (
    "clarification_id, conversation_id, intent_id, state, resume_token, "
    "question_fingerprint, payload, response, client_message_id, created_at, resolved_at"
)


def get_sf_clarification(clarification_id: str) -> Optional[dict]:
    with connection() as con:
        row = con.execute(
            f"SELECT {_CLARIFICATION_COLUMNS} FROM sf_clarifications "
            "WHERE clarification_id = %s",
            (clarification_id,),
        ).fetchone()
    return _clarification_dict(row) if row else None


def pending_sf_clarification(conversation_id: str) -> Optional[dict]:
    """The open question for this conversation, or None."""
    with connection() as con:
        row = con.execute(
            f"SELECT {_CLARIFICATION_COLUMNS} FROM sf_clarifications "
            "WHERE conversation_id = %s AND state = 'pending' "
            "ORDER BY created_at DESC LIMIT 1",
            (conversation_id,),
        ).fetchone()
    return _clarification_dict(row) if row else None


def resolve_sf_clarification(
    clarification_id: str,
    *,
    state: str,
    response: dict,
    client_message_id: Optional[str] = None,
) -> Tuple[Optional[dict], bool]:
    """Answer a pending clarification. → (row, was_already_resolved).

    ONE statement decides the race. `WHERE state = 'pending'` inside the UPDATE
    is what makes the first response win: a double-clicked option, or the same
    fetch retried after a timeout, matches zero rows the second time and gets
    the stored answer back instead of starting a second generation.
    """
    with connection() as con:
        row = con.execute(
            f"UPDATE sf_clarifications SET state = %s, response = %s, "
            "client_message_id = %s, resolved_at = %s "
            f"WHERE clarification_id = %s AND state = 'pending' RETURNING {_CLARIFICATION_COLUMNS}",
            (
                state,
                _json_param(response),
                client_message_id,
                _now(),
                clarification_id,
            ),
        ).fetchone()
        if row is not None:
            return _clarification_dict(row), False
        existing = con.execute(
            f"SELECT {_CLARIFICATION_COLUMNS} FROM sf_clarifications "
            "WHERE clarification_id = %s",
            (clarification_id,),
        ).fetchone()
    if existing is None:
        return None, False
    return _clarification_dict(existing), True


def cancel_sf_clarifications(conversation_id: str) -> int:
    """Cancel every pending question for a conversation (source turned off,
    a clear new topic, the conversation deleted). Returns how many."""
    with connection() as con:
        cur = con.execute(
            "UPDATE sf_clarifications SET state = 'cancelled', resolved_at = %s "
            "WHERE conversation_id = %s AND state = 'pending'",
            (_now(), conversation_id),
        )
        return cur.rowcount


def save_sf_conversation_state(conversation_id: str, payload: dict) -> None:
    with connection() as con:
        con.execute(
            "INSERT INTO sf_conversation_state (conversation_id, payload, updated_at) "
            "VALUES (%s, %s, %s) "
            "ON CONFLICT (conversation_id) DO UPDATE SET "
            "  payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at",
            (conversation_id, _json_param(payload), _now()),
        )


def get_sf_conversation_state(conversation_id: str) -> Optional[dict]:
    with connection() as con:
        row = con.execute(
            "SELECT payload FROM sf_conversation_state WHERE conversation_id = %s",
            (conversation_id,),
        ).fetchone()
    if row is None:
        return None
    return (_row(row) or {}).get("payload") or {}
